package unimodel.constraints;

/*Generated by MPS */

import jetbrains.mps.core.aspects.constraints.rules.BaseRulesConstraintsDescriptor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import jetbrains.mps.core.aspects.constraints.rules.Rule;
import jetbrains.mps.core.aspects.constraints.rules.kinds.ContainmentContext;
import java.util.List;
import java.util.Collections;
import java.util.Arrays;
import org.jetbrains.annotations.NotNull;
import jetbrains.mps.core.aspects.constraints.rules.BaseRule;
import org.jetbrains.mps.openapi.model.SNodeReference;
import org.jetbrains.mps.openapi.persistence.PersistenceFacade;
import jetbrains.mps.core.aspects.constraints.rules.RuleId;
import jetbrains.mps.core.aspects.constraints.rules.kinds.PredefinedRuleKinds;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import org.jetbrains.mps.openapi.language.SProperty;

public final class Book_ConstraintRules extends BaseRulesConstraintsDescriptor {
  private static final SAbstractConcept CONCEPT = MetaAdapterFactory.getConcept(0x6069f38ad5c2473eL, 0xbe656672ae45792cL, 0x79555ffcb891b57fL, "unimodel.structure.Book");

  public static final Rule<ContainmentContext> check_id8742999790642971797 = new Rule_Quantity_Positive();
  public static final Rule<ContainmentContext> check_id8742999790642995291 = new Rule_ISBN_Lenght();
  public static final Rule<ContainmentContext> check_id8742999790643011170 = new Rule_ISBN_Only_Digit();

  private static final List<Rule<?>> RULES = Collections.unmodifiableList(Arrays.<Rule<?>>asList(check_id8742999790642971797, check_id8742999790642995291, check_id8742999790643011170));

  @NotNull
  @Override
  public List<Rule<?>> getDeclaredRules() {
    return RULES;
  }

  public static final class Rule_Quantity_Positive extends BaseRule<ContainmentContext> {
    private static final SNodeReference SOURCE_NODE_REF = PersistenceFacade.getInstance().createNodeReference("r:18f26838-7640-4eda-91b6-ad750b54a45f(unimodel.constraints)/8742999790642971797");
    public static final RuleId ID_Quantity_Positive = new RuleId(8742999790642971797L, SOURCE_NODE_REF);

    public Rule_Quantity_Positive() {
      super(CONCEPT, PredefinedRuleKinds.CAN_BE_CHILD, ID_Quantity_Positive, SOURCE_NODE_REF);
    }

    @Override
    public boolean check(@NotNull ContainmentContext context) {
      return SPropertyOperations.getInteger(context.getChildNode(), PROPS.quantity$QlDV) >= 0;
    }

    @Override
    public boolean appliesTo(@NotNull ContainmentContext context) {
      return true;
    }
  }

  public static final class Rule_ISBN_Lenght extends BaseRule<ContainmentContext> {
    private static final SNodeReference SOURCE_NODE_REF = PersistenceFacade.getInstance().createNodeReference("r:18f26838-7640-4eda-91b6-ad750b54a45f(unimodel.constraints)/8742999790642995291");
    public static final RuleId ID_ISBN_Lenght = new RuleId(8742999790642995291L, SOURCE_NODE_REF);

    public Rule_ISBN_Lenght() {
      super(CONCEPT, PredefinedRuleKinds.CAN_BE_CHILD, ID_ISBN_Lenght, SOURCE_NODE_REF);
    }

    @Override
    public boolean check(@NotNull ContainmentContext context) {
      return SPropertyOperations.getString(context.getChildNode(), PROPS.ISBN$Qr3i).length() == 13;
    }

    @Override
    public boolean appliesTo(@NotNull ContainmentContext context) {
      return true;
    }
  }

  public static final class Rule_ISBN_Only_Digit extends BaseRule<ContainmentContext> {
    private static final SNodeReference SOURCE_NODE_REF = PersistenceFacade.getInstance().createNodeReference("r:18f26838-7640-4eda-91b6-ad750b54a45f(unimodel.constraints)/8742999790643011170");
    public static final RuleId ID_ISBN_Only_Digit = new RuleId(8742999790643011170L, SOURCE_NODE_REF);

    public Rule_ISBN_Only_Digit() {
      super(CONCEPT, PredefinedRuleKinds.CAN_BE_CHILD, ID_ISBN_Only_Digit, SOURCE_NODE_REF);
    }

    @Override
    public boolean check(@NotNull ContainmentContext context) {
      return SPropertyOperations.getString(context.getChildNode(), PROPS.ISBN$Qr3i).matches("[0-9]+");
    }

    @Override
    public boolean appliesTo(@NotNull ContainmentContext context) {
      return true;
    }
  }

  /*package*/ Book_ConstraintRules() {
    super(CONCEPT);
  }

  private static final class PROPS {
    /*package*/ static final SProperty quantity$QlDV = MetaAdapterFactory.getProperty(0x6069f38ad5c2473eL, 0xbe656672ae45792cL, 0x79555ffcb891b57fL, 0x79555ffcb891b582L, "quantity");
    /*package*/ static final SProperty ISBN$Qr3i = MetaAdapterFactory.getProperty(0x6069f38ad5c2473eL, 0xbe656672ae45792cL, 0x79555ffcb891b57fL, 0x79555ffcb891b584L, "ISBN");
  }
}
