package unimodel.constraints;

/*Generated by MPS */

import jetbrains.mps.core.aspects.constraints.rules.BaseRulesConstraintsDescriptor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import java.util.List;
import jetbrains.mps.core.aspects.constraints.rules.Rule;
import java.util.Collections;
import java.util.Arrays;
import org.jetbrains.annotations.NotNull;

public final class University_ConstraintRules extends BaseRulesConstraintsDescriptor {
  private static final SAbstractConcept CONCEPT = MetaAdapterFactory.getConcept(0x6069f38ad5c2473eL, 0xbe656672ae45792cL, 0x79555ffcb891b526L, "unimodel.structure.University");


  private static final List<Rule<?>> RULES = Collections.unmodifiableList(Arrays.<Rule<?>>asList());

  @NotNull
  @Override
  public List<Rule<?>> getDeclaredRules() {
    return RULES;
  }

  /*package*/ University_ConstraintRules() {
    super(CONCEPT);
  }
}
