/*
 * generated by Xtext 2.25.0
 */
package it.univaq.disim.unimodel.xtext.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import it.univaq.disim.unimodel.xtext.ide.contentassist.antlr.internal.InternalUnimodelParser;
import it.univaq.disim.unimodel.xtext.services.UnimodelGrammarAccess;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class UnimodelParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(UnimodelGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, UnimodelGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
			builder.put(grammarAccess.getEFloatAccess().getAlternatives_4_0(), "rule__EFloat__Alternatives_4_0");
			builder.put(grammarAccess.getCategoryAccess().getAlternatives(), "rule__Category__Alternatives");
			builder.put(grammarAccess.getTypeAccess().getAlternatives(), "rule__Type__Alternatives");
			builder.put(grammarAccess.getUniversityAccess().getGroup(), "rule__University__Group__0");
			builder.put(grammarAccess.getUniversityAccess().getGroup_3(), "rule__University__Group_3__0");
			builder.put(grammarAccess.getUniversityAccess().getGroup_4(), "rule__University__Group_4__0");
			builder.put(grammarAccess.getUniversityAccess().getGroup_8(), "rule__University__Group_8__0");
			builder.put(grammarAccess.getBuildingAccess().getGroup(), "rule__Building__Group__0");
			builder.put(grammarAccess.getBuildingAccess().getGroup_3(), "rule__Building__Group_3__0");
			builder.put(grammarAccess.getBuildingAccess().getGroup_6(), "rule__Building__Group_6__0");
			builder.put(grammarAccess.getBuildingAccess().getGroup_10(), "rule__Building__Group_10__0");
			builder.put(grammarAccess.getAddressAccess().getGroup(), "rule__Address__Group__0");
			builder.put(grammarAccess.getAddressAccess().getGroup_4(), "rule__Address__Group_4__0");
			builder.put(grammarAccess.getAddressAccess().getGroup_5(), "rule__Address__Group_5__0");
			builder.put(grammarAccess.getAddressAccess().getGroup_6(), "rule__Address__Group_6__0");
			builder.put(grammarAccess.getAddressAccess().getGroup_7(), "rule__Address__Group_7__0");
			builder.put(grammarAccess.getAddressAccess().getGroup_8(), "rule__Address__Group_8__0");
			builder.put(grammarAccess.getAddressAccess().getGroup_9(), "rule__Address__Group_9__0");
			builder.put(grammarAccess.getAddressAccess().getGroup_10(), "rule__Address__Group_10__0");
			builder.put(grammarAccess.getLibraryAccess().getGroup(), "rule__Library__Group__0");
			builder.put(grammarAccess.getLibraryAccess().getGroup_7(), "rule__Library__Group_7__0");
			builder.put(grammarAccess.getLibraryAccess().getGroup_7_3(), "rule__Library__Group_7_3__0");
			builder.put(grammarAccess.getLibraryAccess().getGroup_8(), "rule__Library__Group_8__0");
			builder.put(grammarAccess.getLibraryAccess().getGroup_8_3(), "rule__Library__Group_8_3__0");
			builder.put(grammarAccess.getLibraryAccess().getGroup_9(), "rule__Library__Group_9__0");
			builder.put(grammarAccess.getLibraryAccess().getGroup_9_3(), "rule__Library__Group_9_3__0");
			builder.put(grammarAccess.getFloorAccess().getGroup(), "rule__Floor__Group__0");
			builder.put(grammarAccess.getFloorAccess().getGroup_6(), "rule__Floor__Group_6__0");
			builder.put(grammarAccess.getFloorAccess().getGroup_6_3(), "rule__Floor__Group_6_3__0");
			builder.put(grammarAccess.getFloorAccess().getGroup_7(), "rule__Floor__Group_7__0");
			builder.put(grammarAccess.getFloorAccess().getGroup_7_3(), "rule__Floor__Group_7_3__0");
			builder.put(grammarAccess.getFloorAccess().getGroup_8(), "rule__Floor__Group_8__0");
			builder.put(grammarAccess.getFloorAccess().getGroup_8_3(), "rule__Floor__Group_8_3__0");
			builder.put(grammarAccess.getEIntAccess().getGroup(), "rule__EInt__Group__0");
			builder.put(grammarAccess.getBookAccess().getGroup(), "rule__Book__Group__0");
			builder.put(grammarAccess.getBookAccess().getGroup_5(), "rule__Book__Group_5__0");
			builder.put(grammarAccess.getBookAccess().getGroup_6(), "rule__Book__Group_6__0");
			builder.put(grammarAccess.getBookAccess().getGroup_7(), "rule__Book__Group_7__0");
			builder.put(grammarAccess.getLoanAccess().getGroup(), "rule__Loan__Group__0");
			builder.put(grammarAccess.getLoanAccess().getGroup_4(), "rule__Loan__Group_4__0");
			builder.put(grammarAccess.getLoanAccess().getGroup_5(), "rule__Loan__Group_5__0");
			builder.put(grammarAccess.getPersonAccess().getGroup(), "rule__Person__Group__0");
			builder.put(grammarAccess.getPersonAccess().getGroup_5(), "rule__Person__Group_5__0");
			builder.put(grammarAccess.getPersonAccess().getGroup_8(), "rule__Person__Group_8__0");
			builder.put(grammarAccess.getPersonAccess().getGroup_9(), "rule__Person__Group_9__0");
			builder.put(grammarAccess.getRoomAccess().getGroup(), "rule__Room__Group__0");
			builder.put(grammarAccess.getOfficeAccess().getGroup(), "rule__Office__Group__0");
			builder.put(grammarAccess.getOfficeAccess().getGroup_7(), "rule__Office__Group_7__0");
			builder.put(grammarAccess.getOfficeAccess().getGroup_17(), "rule__Office__Group_17__0");
			builder.put(grammarAccess.getClassAccess().getGroup(), "rule__Class__Group__0");
			builder.put(grammarAccess.getEFloatAccess().getGroup(), "rule__EFloat__Group__0");
			builder.put(grammarAccess.getEFloatAccess().getGroup_4(), "rule__EFloat__Group_4__0");
			builder.put(grammarAccess.getUniversityAccess().getNameAssignment_1(), "rule__University__NameAssignment_1");
			builder.put(grammarAccess.getUniversityAccess().getChancellorAssignment_3_1(), "rule__University__ChancellorAssignment_3_1");
			builder.put(grammarAccess.getUniversityAccess().getDescriptionAssignment_4_1(), "rule__University__DescriptionAssignment_4_1");
			builder.put(grammarAccess.getUniversityAccess().getBuildingsAssignment_7(), "rule__University__BuildingsAssignment_7");
			builder.put(grammarAccess.getUniversityAccess().getBuildingsAssignment_8_1(), "rule__University__BuildingsAssignment_8_1");
			builder.put(grammarAccess.getBuildingAccess().getNameAssignment_1(), "rule__Building__NameAssignment_1");
			builder.put(grammarAccess.getBuildingAccess().getDescriptionAssignment_3_1(), "rule__Building__DescriptionAssignment_3_1");
			builder.put(grammarAccess.getBuildingAccess().getAddressAssignment_5(), "rule__Building__AddressAssignment_5");
			builder.put(grammarAccess.getBuildingAccess().getLibraryAssignment_6_1(), "rule__Building__LibraryAssignment_6_1");
			builder.put(grammarAccess.getBuildingAccess().getFloorsAssignment_9(), "rule__Building__FloorsAssignment_9");
			builder.put(grammarAccess.getBuildingAccess().getFloorsAssignment_10_1(), "rule__Building__FloorsAssignment_10_1");
			builder.put(grammarAccess.getAddressAccess().getIdAssignment_2(), "rule__Address__IdAssignment_2");
			builder.put(grammarAccess.getAddressAccess().getCountryAssignment_4_1(), "rule__Address__CountryAssignment_4_1");
			builder.put(grammarAccess.getAddressAccess().getStateAssignment_5_1(), "rule__Address__StateAssignment_5_1");
			builder.put(grammarAccess.getAddressAccess().getCityAssignment_6_1(), "rule__Address__CityAssignment_6_1");
			builder.put(grammarAccess.getAddressAccess().getPost_codeAssignment_7_1(), "rule__Address__Post_codeAssignment_7_1");
			builder.put(grammarAccess.getAddressAccess().getStreetAssignment_8_1(), "rule__Address__StreetAssignment_8_1");
			builder.put(grammarAccess.getAddressAccess().getCivicAssignment_9_1(), "rule__Address__CivicAssignment_9_1");
			builder.put(grammarAccess.getAddressAccess().getPhoneAssignment_10_1(), "rule__Address__PhoneAssignment_10_1");
			builder.put(grammarAccess.getLibraryAccess().getNameAssignment_1(), "rule__Library__NameAssignment_1");
			builder.put(grammarAccess.getLibraryAccess().getWorkstationsAssignment_4(), "rule__Library__WorkstationsAssignment_4");
			builder.put(grammarAccess.getLibraryAccess().getComputersAssignment_6(), "rule__Library__ComputersAssignment_6");
			builder.put(grammarAccess.getLibraryAccess().getBooksAssignment_7_2(), "rule__Library__BooksAssignment_7_2");
			builder.put(grammarAccess.getLibraryAccess().getBooksAssignment_7_3_1(), "rule__Library__BooksAssignment_7_3_1");
			builder.put(grammarAccess.getLibraryAccess().getLoansAssignment_8_2(), "rule__Library__LoansAssignment_8_2");
			builder.put(grammarAccess.getLibraryAccess().getLoansAssignment_8_3_1(), "rule__Library__LoansAssignment_8_3_1");
			builder.put(grammarAccess.getLibraryAccess().getPersonAssignment_9_2(), "rule__Library__PersonAssignment_9_2");
			builder.put(grammarAccess.getLibraryAccess().getPersonAssignment_9_3_1(), "rule__Library__PersonAssignment_9_3_1");
			builder.put(grammarAccess.getFloorAccess().getNumberAssignment_3(), "rule__Floor__NumberAssignment_3");
			builder.put(grammarAccess.getFloorAccess().getBathroomsAssignment_5(), "rule__Floor__BathroomsAssignment_5");
			builder.put(grammarAccess.getFloorAccess().getOfficesAssignment_6_2(), "rule__Floor__OfficesAssignment_6_2");
			builder.put(grammarAccess.getFloorAccess().getOfficesAssignment_6_3_1(), "rule__Floor__OfficesAssignment_6_3_1");
			builder.put(grammarAccess.getFloorAccess().getClassesAssignment_7_2(), "rule__Floor__ClassesAssignment_7_2");
			builder.put(grammarAccess.getFloorAccess().getClassesAssignment_7_3_1(), "rule__Floor__ClassesAssignment_7_3_1");
			builder.put(grammarAccess.getFloorAccess().getRoomsAssignment_8_2(), "rule__Floor__RoomsAssignment_8_2");
			builder.put(grammarAccess.getFloorAccess().getRoomsAssignment_8_3_1(), "rule__Floor__RoomsAssignment_8_3_1");
			builder.put(grammarAccess.getBookAccess().getNameAssignment_1(), "rule__Book__NameAssignment_1");
			builder.put(grammarAccess.getBookAccess().getQuantityAssignment_4(), "rule__Book__QuantityAssignment_4");
			builder.put(grammarAccess.getBookAccess().getISBNAssignment_5_1(), "rule__Book__ISBNAssignment_5_1");
			builder.put(grammarAccess.getBookAccess().getAuthorAssignment_6_1(), "rule__Book__AuthorAssignment_6_1");
			builder.put(grammarAccess.getBookAccess().getLibraryAssignment_7_1(), "rule__Book__LibraryAssignment_7_1");
			builder.put(grammarAccess.getLoanAccess().getDateAssignment_3(), "rule__Loan__DateAssignment_3");
			builder.put(grammarAccess.getLoanAccess().getBookAssignment_4_1(), "rule__Loan__BookAssignment_4_1");
			builder.put(grammarAccess.getLoanAccess().getPersonAssignment_5_1(), "rule__Loan__PersonAssignment_5_1");
			builder.put(grammarAccess.getPersonAccess().getNameAssignment_1(), "rule__Person__NameAssignment_1");
			builder.put(grammarAccess.getPersonAccess().getCategoryAssignment_4(), "rule__Person__CategoryAssignment_4");
			builder.put(grammarAccess.getPersonAccess().getBadgeAssignment_5_1(), "rule__Person__BadgeAssignment_5_1");
			builder.put(grammarAccess.getPersonAccess().getAgeAssignment_7(), "rule__Person__AgeAssignment_7");
			builder.put(grammarAccess.getPersonAccess().getFiscal_codeAssignment_8_1(), "rule__Person__Fiscal_codeAssignment_8_1");
			builder.put(grammarAccess.getPersonAccess().getLibraryAssignment_9_1(), "rule__Person__LibraryAssignment_9_1");
			builder.put(grammarAccess.getRoomAccess().getNameAssignment_1(), "rule__Room__NameAssignment_1");
			builder.put(grammarAccess.getRoomAccess().getDimensionAssignment_4(), "rule__Room__DimensionAssignment_4");
			builder.put(grammarAccess.getRoomAccess().getSocketsAssignment_6(), "rule__Room__SocketsAssignment_6");
			builder.put(grammarAccess.getOfficeAccess().getNameAssignment_1(), "rule__Office__NameAssignment_1");
			builder.put(grammarAccess.getOfficeAccess().getTypeAssignment_4(), "rule__Office__TypeAssignment_4");
			builder.put(grammarAccess.getOfficeAccess().getCapacityAssignment_6(), "rule__Office__CapacityAssignment_6");
			builder.put(grammarAccess.getOfficeAccess().getPhoneAssignment_7_1(), "rule__Office__PhoneAssignment_7_1");
			builder.put(grammarAccess.getOfficeAccess().getDimensionAssignment_9(), "rule__Office__DimensionAssignment_9");
			builder.put(grammarAccess.getOfficeAccess().getSocketsAssignment_11(), "rule__Office__SocketsAssignment_11");
			builder.put(grammarAccess.getOfficeAccess().getOffice_addressAssignment_13(), "rule__Office__Office_addressAssignment_13");
			builder.put(grammarAccess.getOfficeAccess().getPerson_in_officeAssignment_16(), "rule__Office__Person_in_officeAssignment_16");
			builder.put(grammarAccess.getOfficeAccess().getPerson_in_officeAssignment_17_1(), "rule__Office__Person_in_officeAssignment_17_1");
			builder.put(grammarAccess.getClassAccess().getNameAssignment_1(), "rule__Class__NameAssignment_1");
			builder.put(grammarAccess.getClassAccess().getSeatsAssignment_4(), "rule__Class__SeatsAssignment_4");
			builder.put(grammarAccess.getClassAccess().getBlackboardsAssignment_6(), "rule__Class__BlackboardsAssignment_6");
			builder.put(grammarAccess.getClassAccess().getSpeakersAssignment_8(), "rule__Class__SpeakersAssignment_8");
			builder.put(grammarAccess.getClassAccess().getComputersAssignment_10(), "rule__Class__ComputersAssignment_10");
			builder.put(grammarAccess.getClassAccess().getDimensionAssignment_12(), "rule__Class__DimensionAssignment_12");
			builder.put(grammarAccess.getClassAccess().getSocketsAssignment_14(), "rule__Class__SocketsAssignment_14");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private UnimodelGrammarAccess grammarAccess;

	@Override
	protected InternalUnimodelParser createParser() {
		InternalUnimodelParser result = new InternalUnimodelParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public UnimodelGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(UnimodelGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
