/*
 * generated by Xtext 2.25.0
 */
package it.univaq.disim.unimodel.xtext


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class UnimodelRuntimeModule extends AbstractUnimodelRuntimeModule {
}
