<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="unimodel_webapp" nsURI="http://www.example.org/unimodel_webapp"
    nsPrefix="unimodel_webapp">
  <eClassifiers xsi:type="ecore:EClass" name="Application" eSuperTypes="#//Named">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Description" lowerBound="1"
        eType="#//Description" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Department_Page" lowerBound="1"
        upperBound="-1" eType="#//Building_Page" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="users" upperBound="-1"
        eType="#//User" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Building_Page" eSuperTypes="#//Named">
    <eStructuralFeatures xsi:type="ecore:EReference" name="info" lowerBound="1" eType="#//Info"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="library_page" eType="#//Library_Page"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="map_section" lowerBound="1"
        upperBound="-1" eType="#//Map_Section" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Map_Section">
    <eStructuralFeatures xsi:type="ecore:EReference" name="room" upperBound="-1" eType="#//Room"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="number" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="number_bathrooms" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Room" eSuperTypes="#//Named">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dimension" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sockets" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Class" eSuperTypes="#//Room">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="seats" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="number_computers" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="number_blackboars" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="number_speakers" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Office" eSuperTypes="#//Room">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="#//Type"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="capacity" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="person_in_office" eType="#//User"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="office_info" eType="#//Info"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Library_Page" eSuperTypes="#//Named">
    <eStructuralFeatures xsi:type="ecore:EReference" name="books" upperBound="-1"
        eType="#//Book" containment="true" eOpposite="#//Book/library"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="loans" upperBound="-1"
        eType="#//Loan" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="workstation" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="computers" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Loan">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="date" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="book" eType="#//Book"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="user" eType="#//User"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="User" eSuperTypes="#//Named">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="username" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="age" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="badge" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="category" lowerBound="1"
        eType="#//Category"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="loans" upperBound="-1"
        eType="#//Loan" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Book" eSuperTypes="#//Named">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="quantity" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ISBN" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="author" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="library" eType="#//Library_Page"
        eOpposite="#//Library_Page/books"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="books" upperBound="-1"
        eType="#//Book" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="loans" upperBound="-1"
        eType="#//Loan"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Info">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="phone" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="country" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="state" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="city" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="postcode" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="street" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="civic" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Description">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="chancellor" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Named">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Type">
    <eLiterals name="PROFESSOR_OFFICE"/>
    <eLiterals name="PHD_ROOM" value="1"/>
    <eLiterals name="ADMINISTRATION" value="2"/>
    <eLiterals name="SECRETARIAT" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Category">
    <eLiterals name="PROFESSOR"/>
    <eLiterals name="PHD_STUDENT" value="1"/>
    <eLiterals name="ADMINISTRATOR" value="2"/>
    <eLiterals name="STAFF" value="3"/>
    <eLiterals name="STUDENT" value="4"/>
  </eClassifiers>
</ecore:EPackage>
