/*
 * generated by Xtext 2.25.0
 */
package it.univaq.disim.unimodel.xtext.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.EnumLiteralDeclaration;
import org.eclipse.xtext.EnumRule;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class UnimodelGrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class UniversityElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "it.univaq.disim.unimodel.xtext.Unimodel.University");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cUniversityKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cChancellorKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cChancellorAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cChancellorEStringParserRuleCall_3_1_0 = (RuleCall)cChancellorAssignment_3_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cDescriptionKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cDescriptionAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cDescriptionEStringParserRuleCall_4_1_0 = (RuleCall)cDescriptionAssignment_4_1.eContents().get(0);
		private final Keyword cBuildingsKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Keyword cLeftCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cBuildingsAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cBuildingsBuildingParserRuleCall_7_0 = (RuleCall)cBuildingsAssignment_7.eContents().get(0);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cCommaKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Assignment cBuildingsAssignment_8_1 = (Assignment)cGroup_8.eContents().get(1);
		private final RuleCall cBuildingsBuildingParserRuleCall_8_1_0 = (RuleCall)cBuildingsAssignment_8_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Keyword cRightCurlyBracketKeyword_10 = (Keyword)cGroup.eContents().get(10);
		
		//University returns University:
		//    'University'
		//    name=EString
		//    '{'
		//        ('chancellor' chancellor=EString)?
		//        ('description' description=EString)?
		//        'buildings' '{' buildings+=Building ( "," buildings+=Building)* '}'
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'University'
		//name=EString
		//'{'
		//    ('chancellor' chancellor=EString)?
		//    ('description' description=EString)?
		//    'buildings' '{' buildings+=Building ( "," buildings+=Building)* '}'
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'University'
		public Keyword getUniversityKeyword_0() { return cUniversityKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('chancellor' chancellor=EString)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'chancellor'
		public Keyword getChancellorKeyword_3_0() { return cChancellorKeyword_3_0; }
		
		//chancellor=EString
		public Assignment getChancellorAssignment_3_1() { return cChancellorAssignment_3_1; }
		
		//EString
		public RuleCall getChancellorEStringParserRuleCall_3_1_0() { return cChancellorEStringParserRuleCall_3_1_0; }
		
		//('description' description=EString)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'description'
		public Keyword getDescriptionKeyword_4_0() { return cDescriptionKeyword_4_0; }
		
		//description=EString
		public Assignment getDescriptionAssignment_4_1() { return cDescriptionAssignment_4_1; }
		
		//EString
		public RuleCall getDescriptionEStringParserRuleCall_4_1_0() { return cDescriptionEStringParserRuleCall_4_1_0; }
		
		//'buildings'
		public Keyword getBuildingsKeyword_5() { return cBuildingsKeyword_5; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_6() { return cLeftCurlyBracketKeyword_6; }
		
		//buildings+=Building
		public Assignment getBuildingsAssignment_7() { return cBuildingsAssignment_7; }
		
		//Building
		public RuleCall getBuildingsBuildingParserRuleCall_7_0() { return cBuildingsBuildingParserRuleCall_7_0; }
		
		//( "," buildings+=Building)*
		public Group getGroup_8() { return cGroup_8; }
		
		//","
		public Keyword getCommaKeyword_8_0() { return cCommaKeyword_8_0; }
		
		//buildings+=Building
		public Assignment getBuildingsAssignment_8_1() { return cBuildingsAssignment_8_1; }
		
		//Building
		public RuleCall getBuildingsBuildingParserRuleCall_8_1_0() { return cBuildingsBuildingParserRuleCall_8_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_9() { return cRightCurlyBracketKeyword_9; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_10() { return cRightCurlyBracketKeyword_10; }
	}
	public class RoomElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "it.univaq.disim.unimodel.xtext.Unimodel.Room");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cRoom_ImplParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cOfficeParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cClassParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		
		//Room returns Room:
		//    Room_Impl | Office | Class;
		@Override public ParserRule getRule() { return rule; }
		
		//Room_Impl | Office | Class
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Room_Impl
		public RuleCall getRoom_ImplParserRuleCall_0() { return cRoom_ImplParserRuleCall_0; }
		
		//Office
		public RuleCall getOfficeParserRuleCall_1() { return cOfficeParserRuleCall_1; }
		
		//Class
		public RuleCall getClassParserRuleCall_2() { return cClassParserRuleCall_2; }
	}
	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "it.univaq.disim.unimodel.xtext.Unimodel.EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString returns ecore::EString:
		//    STRING | ID;
		@Override public ParserRule getRule() { return rule; }
		
		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}
	public class BuildingElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "it.univaq.disim.unimodel.xtext.Unimodel.Building");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cBuildingKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cDescriptionKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cDescriptionAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cDescriptionEStringParserRuleCall_3_1_0 = (RuleCall)cDescriptionAssignment_3_1.eContents().get(0);
		private final Keyword cAddressKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cAddressAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cAddressAddressParserRuleCall_5_0 = (RuleCall)cAddressAssignment_5.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cLibraryKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cLibraryAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cLibraryLibraryParserRuleCall_6_1_0 = (RuleCall)cLibraryAssignment_6_1.eContents().get(0);
		private final Keyword cFloorsKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Keyword cLeftCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Assignment cFloorsAssignment_9 = (Assignment)cGroup.eContents().get(9);
		private final RuleCall cFloorsFloorParserRuleCall_9_0 = (RuleCall)cFloorsAssignment_9.eContents().get(0);
		private final Group cGroup_10 = (Group)cGroup.eContents().get(10);
		private final Keyword cCommaKeyword_10_0 = (Keyword)cGroup_10.eContents().get(0);
		private final Assignment cFloorsAssignment_10_1 = (Assignment)cGroup_10.eContents().get(1);
		private final RuleCall cFloorsFloorParserRuleCall_10_1_0 = (RuleCall)cFloorsAssignment_10_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_11 = (Keyword)cGroup.eContents().get(11);
		private final Keyword cRightCurlyBracketKeyword_12 = (Keyword)cGroup.eContents().get(12);
		
		//Building returns Building:
		//    'Building'
		//    name=EString
		//    '{'
		//        ('description' description=EString)?
		//        'address' address=Address
		//        ('library' library=Library)?
		//        'floors' '{' floors+=Floor ( "," floors+=Floor)* '}'
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Building'
		//name=EString
		//'{'
		//    ('description' description=EString)?
		//    'address' address=Address
		//    ('library' library=Library)?
		//    'floors' '{' floors+=Floor ( "," floors+=Floor)* '}'
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'Building'
		public Keyword getBuildingKeyword_0() { return cBuildingKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('description' description=EString)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'description'
		public Keyword getDescriptionKeyword_3_0() { return cDescriptionKeyword_3_0; }
		
		//description=EString
		public Assignment getDescriptionAssignment_3_1() { return cDescriptionAssignment_3_1; }
		
		//EString
		public RuleCall getDescriptionEStringParserRuleCall_3_1_0() { return cDescriptionEStringParserRuleCall_3_1_0; }
		
		//'address'
		public Keyword getAddressKeyword_4() { return cAddressKeyword_4; }
		
		//address=Address
		public Assignment getAddressAssignment_5() { return cAddressAssignment_5; }
		
		//Address
		public RuleCall getAddressAddressParserRuleCall_5_0() { return cAddressAddressParserRuleCall_5_0; }
		
		//('library' library=Library)?
		public Group getGroup_6() { return cGroup_6; }
		
		//'library'
		public Keyword getLibraryKeyword_6_0() { return cLibraryKeyword_6_0; }
		
		//library=Library
		public Assignment getLibraryAssignment_6_1() { return cLibraryAssignment_6_1; }
		
		//Library
		public RuleCall getLibraryLibraryParserRuleCall_6_1_0() { return cLibraryLibraryParserRuleCall_6_1_0; }
		
		//'floors'
		public Keyword getFloorsKeyword_7() { return cFloorsKeyword_7; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_8() { return cLeftCurlyBracketKeyword_8; }
		
		//floors+=Floor
		public Assignment getFloorsAssignment_9() { return cFloorsAssignment_9; }
		
		//Floor
		public RuleCall getFloorsFloorParserRuleCall_9_0() { return cFloorsFloorParserRuleCall_9_0; }
		
		//( "," floors+=Floor)*
		public Group getGroup_10() { return cGroup_10; }
		
		//","
		public Keyword getCommaKeyword_10_0() { return cCommaKeyword_10_0; }
		
		//floors+=Floor
		public Assignment getFloorsAssignment_10_1() { return cFloorsAssignment_10_1; }
		
		//Floor
		public RuleCall getFloorsFloorParserRuleCall_10_1_0() { return cFloorsFloorParserRuleCall_10_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_11() { return cRightCurlyBracketKeyword_11; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_12() { return cRightCurlyBracketKeyword_12; }
	}
	public class AddressElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "it.univaq.disim.unimodel.xtext.Unimodel.Address");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cAddressAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cAddressKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cIdAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cIdEIntParserRuleCall_2_0 = (RuleCall)cIdAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cCountryKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cCountryAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cCountryEStringParserRuleCall_4_1_0 = (RuleCall)cCountryAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cStateKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cStateAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cStateEStringParserRuleCall_5_1_0 = (RuleCall)cStateAssignment_5_1.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cCityKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cCityAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cCityEStringParserRuleCall_6_1_0 = (RuleCall)cCityAssignment_6_1.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cPost_codeKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cPost_codeAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final RuleCall cPost_codeEStringParserRuleCall_7_1_0 = (RuleCall)cPost_codeAssignment_7_1.eContents().get(0);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cStreetKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Assignment cStreetAssignment_8_1 = (Assignment)cGroup_8.eContents().get(1);
		private final RuleCall cStreetEStringParserRuleCall_8_1_0 = (RuleCall)cStreetAssignment_8_1.eContents().get(0);
		private final Group cGroup_9 = (Group)cGroup.eContents().get(9);
		private final Keyword cCivicKeyword_9_0 = (Keyword)cGroup_9.eContents().get(0);
		private final Assignment cCivicAssignment_9_1 = (Assignment)cGroup_9.eContents().get(1);
		private final RuleCall cCivicEStringParserRuleCall_9_1_0 = (RuleCall)cCivicAssignment_9_1.eContents().get(0);
		private final Group cGroup_10 = (Group)cGroup.eContents().get(10);
		private final Keyword cPhoneKeyword_10_0 = (Keyword)cGroup_10.eContents().get(0);
		private final Assignment cPhoneAssignment_10_1 = (Assignment)cGroup_10.eContents().get(1);
		private final RuleCall cPhoneEStringParserRuleCall_10_1_0 = (RuleCall)cPhoneAssignment_10_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_11 = (Keyword)cGroup.eContents().get(11);
		
		//Address returns Address:
		//    {Address}
		//    'Address'
		//    id=EInt
		//    '{'
		//        ('country' country=EString)?
		//        ('state' state=EString)?
		//        ('city' city=EString)?
		//        ('post_code' post_code=EString)?
		//        ('street' street=EString)?
		//        ('civic' civic=EString)?
		//        ('phone' phone=EString)?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Address}
		//'Address'
		//id=EInt
		//'{'
		//    ('country' country=EString)?
		//    ('state' state=EString)?
		//    ('city' city=EString)?
		//    ('post_code' post_code=EString)?
		//    ('street' street=EString)?
		//    ('civic' civic=EString)?
		//    ('phone' phone=EString)?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{Address}
		public Action getAddressAction_0() { return cAddressAction_0; }
		
		//'Address'
		public Keyword getAddressKeyword_1() { return cAddressKeyword_1; }
		
		//id=EInt
		public Assignment getIdAssignment_2() { return cIdAssignment_2; }
		
		//EInt
		public RuleCall getIdEIntParserRuleCall_2_0() { return cIdEIntParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('country' country=EString)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'country'
		public Keyword getCountryKeyword_4_0() { return cCountryKeyword_4_0; }
		
		//country=EString
		public Assignment getCountryAssignment_4_1() { return cCountryAssignment_4_1; }
		
		//EString
		public RuleCall getCountryEStringParserRuleCall_4_1_0() { return cCountryEStringParserRuleCall_4_1_0; }
		
		//('state' state=EString)?
		public Group getGroup_5() { return cGroup_5; }
		
		//'state'
		public Keyword getStateKeyword_5_0() { return cStateKeyword_5_0; }
		
		//state=EString
		public Assignment getStateAssignment_5_1() { return cStateAssignment_5_1; }
		
		//EString
		public RuleCall getStateEStringParserRuleCall_5_1_0() { return cStateEStringParserRuleCall_5_1_0; }
		
		//('city' city=EString)?
		public Group getGroup_6() { return cGroup_6; }
		
		//'city'
		public Keyword getCityKeyword_6_0() { return cCityKeyword_6_0; }
		
		//city=EString
		public Assignment getCityAssignment_6_1() { return cCityAssignment_6_1; }
		
		//EString
		public RuleCall getCityEStringParserRuleCall_6_1_0() { return cCityEStringParserRuleCall_6_1_0; }
		
		//('post_code' post_code=EString)?
		public Group getGroup_7() { return cGroup_7; }
		
		//'post_code'
		public Keyword getPost_codeKeyword_7_0() { return cPost_codeKeyword_7_0; }
		
		//post_code=EString
		public Assignment getPost_codeAssignment_7_1() { return cPost_codeAssignment_7_1; }
		
		//EString
		public RuleCall getPost_codeEStringParserRuleCall_7_1_0() { return cPost_codeEStringParserRuleCall_7_1_0; }
		
		//('street' street=EString)?
		public Group getGroup_8() { return cGroup_8; }
		
		//'street'
		public Keyword getStreetKeyword_8_0() { return cStreetKeyword_8_0; }
		
		//street=EString
		public Assignment getStreetAssignment_8_1() { return cStreetAssignment_8_1; }
		
		//EString
		public RuleCall getStreetEStringParserRuleCall_8_1_0() { return cStreetEStringParserRuleCall_8_1_0; }
		
		//('civic' civic=EString)?
		public Group getGroup_9() { return cGroup_9; }
		
		//'civic'
		public Keyword getCivicKeyword_9_0() { return cCivicKeyword_9_0; }
		
		//civic=EString
		public Assignment getCivicAssignment_9_1() { return cCivicAssignment_9_1; }
		
		//EString
		public RuleCall getCivicEStringParserRuleCall_9_1_0() { return cCivicEStringParserRuleCall_9_1_0; }
		
		//('phone' phone=EString)?
		public Group getGroup_10() { return cGroup_10; }
		
		//'phone'
		public Keyword getPhoneKeyword_10_0() { return cPhoneKeyword_10_0; }
		
		//phone=EString
		public Assignment getPhoneAssignment_10_1() { return cPhoneAssignment_10_1; }
		
		//EString
		public RuleCall getPhoneEStringParserRuleCall_10_1_0() { return cPhoneEStringParserRuleCall_10_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_11() { return cRightCurlyBracketKeyword_11; }
	}
	public class LibraryElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "it.univaq.disim.unimodel.xtext.Unimodel.Library");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLibraryKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cWorkstationsKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cWorkstationsAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cWorkstationsEIntParserRuleCall_4_0 = (RuleCall)cWorkstationsAssignment_4.eContents().get(0);
		private final Keyword cComputersKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cComputersAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cComputersEIntParserRuleCall_6_0 = (RuleCall)cComputersAssignment_6.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cBooksKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_7_1 = (Keyword)cGroup_7.eContents().get(1);
		private final Assignment cBooksAssignment_7_2 = (Assignment)cGroup_7.eContents().get(2);
		private final RuleCall cBooksBookParserRuleCall_7_2_0 = (RuleCall)cBooksAssignment_7_2.eContents().get(0);
		private final Group cGroup_7_3 = (Group)cGroup_7.eContents().get(3);
		private final Keyword cCommaKeyword_7_3_0 = (Keyword)cGroup_7_3.eContents().get(0);
		private final Assignment cBooksAssignment_7_3_1 = (Assignment)cGroup_7_3.eContents().get(1);
		private final RuleCall cBooksBookParserRuleCall_7_3_1_0 = (RuleCall)cBooksAssignment_7_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7_4 = (Keyword)cGroup_7.eContents().get(4);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cLoansKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_8_1 = (Keyword)cGroup_8.eContents().get(1);
		private final Assignment cLoansAssignment_8_2 = (Assignment)cGroup_8.eContents().get(2);
		private final RuleCall cLoansLoanParserRuleCall_8_2_0 = (RuleCall)cLoansAssignment_8_2.eContents().get(0);
		private final Group cGroup_8_3 = (Group)cGroup_8.eContents().get(3);
		private final Keyword cCommaKeyword_8_3_0 = (Keyword)cGroup_8_3.eContents().get(0);
		private final Assignment cLoansAssignment_8_3_1 = (Assignment)cGroup_8_3.eContents().get(1);
		private final RuleCall cLoansLoanParserRuleCall_8_3_1_0 = (RuleCall)cLoansAssignment_8_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_8_4 = (Keyword)cGroup_8.eContents().get(4);
		private final Group cGroup_9 = (Group)cGroup.eContents().get(9);
		private final Keyword cPersonKeyword_9_0 = (Keyword)cGroup_9.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_9_1 = (Keyword)cGroup_9.eContents().get(1);
		private final Assignment cPersonAssignment_9_2 = (Assignment)cGroup_9.eContents().get(2);
		private final RuleCall cPersonPersonParserRuleCall_9_2_0 = (RuleCall)cPersonAssignment_9_2.eContents().get(0);
		private final Group cGroup_9_3 = (Group)cGroup_9.eContents().get(3);
		private final Keyword cCommaKeyword_9_3_0 = (Keyword)cGroup_9_3.eContents().get(0);
		private final Assignment cPersonAssignment_9_3_1 = (Assignment)cGroup_9_3.eContents().get(1);
		private final RuleCall cPersonPersonParserRuleCall_9_3_1_0 = (RuleCall)cPersonAssignment_9_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_9_4 = (Keyword)cGroup_9.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_10 = (Keyword)cGroup.eContents().get(10);
		
		//Library returns Library:
		//    'Library'
		//    name=EString
		//    '{'
		//        'workstations' workstations=EInt
		//        'computers' computers=EInt
		//        ('books' '{' books+=Book ( "," books+=Book)* '}' )?
		//        ('loans' '{' loans+=Loan ( "," loans+=Loan)* '}' )?
		//        ('person' '{' person+=Person ( "," person+=Person)* '}' )?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Library'
		//name=EString
		//'{'
		//    'workstations' workstations=EInt
		//    'computers' computers=EInt
		//    ('books' '{' books+=Book ( "," books+=Book)* '}' )?
		//    ('loans' '{' loans+=Loan ( "," loans+=Loan)* '}' )?
		//    ('person' '{' person+=Person ( "," person+=Person)* '}' )?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'Library'
		public Keyword getLibraryKeyword_0() { return cLibraryKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//'workstations'
		public Keyword getWorkstationsKeyword_3() { return cWorkstationsKeyword_3; }
		
		//workstations=EInt
		public Assignment getWorkstationsAssignment_4() { return cWorkstationsAssignment_4; }
		
		//EInt
		public RuleCall getWorkstationsEIntParserRuleCall_4_0() { return cWorkstationsEIntParserRuleCall_4_0; }
		
		//'computers'
		public Keyword getComputersKeyword_5() { return cComputersKeyword_5; }
		
		//computers=EInt
		public Assignment getComputersAssignment_6() { return cComputersAssignment_6; }
		
		//EInt
		public RuleCall getComputersEIntParserRuleCall_6_0() { return cComputersEIntParserRuleCall_6_0; }
		
		//('books' '{' books+=Book ( "," books+=Book)* '}' )?
		public Group getGroup_7() { return cGroup_7; }
		
		//'books'
		public Keyword getBooksKeyword_7_0() { return cBooksKeyword_7_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_7_1() { return cLeftCurlyBracketKeyword_7_1; }
		
		//books+=Book
		public Assignment getBooksAssignment_7_2() { return cBooksAssignment_7_2; }
		
		//Book
		public RuleCall getBooksBookParserRuleCall_7_2_0() { return cBooksBookParserRuleCall_7_2_0; }
		
		//( "," books+=Book)*
		public Group getGroup_7_3() { return cGroup_7_3; }
		
		//","
		public Keyword getCommaKeyword_7_3_0() { return cCommaKeyword_7_3_0; }
		
		//books+=Book
		public Assignment getBooksAssignment_7_3_1() { return cBooksAssignment_7_3_1; }
		
		//Book
		public RuleCall getBooksBookParserRuleCall_7_3_1_0() { return cBooksBookParserRuleCall_7_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7_4() { return cRightCurlyBracketKeyword_7_4; }
		
		//('loans' '{' loans+=Loan ( "," loans+=Loan)* '}' )?
		public Group getGroup_8() { return cGroup_8; }
		
		//'loans'
		public Keyword getLoansKeyword_8_0() { return cLoansKeyword_8_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_8_1() { return cLeftCurlyBracketKeyword_8_1; }
		
		//loans+=Loan
		public Assignment getLoansAssignment_8_2() { return cLoansAssignment_8_2; }
		
		//Loan
		public RuleCall getLoansLoanParserRuleCall_8_2_0() { return cLoansLoanParserRuleCall_8_2_0; }
		
		//( "," loans+=Loan)*
		public Group getGroup_8_3() { return cGroup_8_3; }
		
		//","
		public Keyword getCommaKeyword_8_3_0() { return cCommaKeyword_8_3_0; }
		
		//loans+=Loan
		public Assignment getLoansAssignment_8_3_1() { return cLoansAssignment_8_3_1; }
		
		//Loan
		public RuleCall getLoansLoanParserRuleCall_8_3_1_0() { return cLoansLoanParserRuleCall_8_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_8_4() { return cRightCurlyBracketKeyword_8_4; }
		
		//('person' '{' person+=Person ( "," person+=Person)* '}' )?
		public Group getGroup_9() { return cGroup_9; }
		
		//'person'
		public Keyword getPersonKeyword_9_0() { return cPersonKeyword_9_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_9_1() { return cLeftCurlyBracketKeyword_9_1; }
		
		//person+=Person
		public Assignment getPersonAssignment_9_2() { return cPersonAssignment_9_2; }
		
		//Person
		public RuleCall getPersonPersonParserRuleCall_9_2_0() { return cPersonPersonParserRuleCall_9_2_0; }
		
		//( "," person+=Person)*
		public Group getGroup_9_3() { return cGroup_9_3; }
		
		//","
		public Keyword getCommaKeyword_9_3_0() { return cCommaKeyword_9_3_0; }
		
		//person+=Person
		public Assignment getPersonAssignment_9_3_1() { return cPersonAssignment_9_3_1; }
		
		//Person
		public RuleCall getPersonPersonParserRuleCall_9_3_1_0() { return cPersonPersonParserRuleCall_9_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_9_4() { return cRightCurlyBracketKeyword_9_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_10() { return cRightCurlyBracketKeyword_10; }
	}
	public class FloorElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "it.univaq.disim.unimodel.xtext.Unimodel.Floor");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cFloorKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cNumberKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cNumberAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cNumberEIntParserRuleCall_3_0 = (RuleCall)cNumberAssignment_3.eContents().get(0);
		private final Keyword cBathroomsKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cBathroomsAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cBathroomsEIntParserRuleCall_5_0 = (RuleCall)cBathroomsAssignment_5.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cRoomsKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_6_1 = (Keyword)cGroup_6.eContents().get(1);
		private final Assignment cRoomsAssignment_6_2 = (Assignment)cGroup_6.eContents().get(2);
		private final RuleCall cRoomsRoomParserRuleCall_6_2_0 = (RuleCall)cRoomsAssignment_6_2.eContents().get(0);
		private final Group cGroup_6_3 = (Group)cGroup_6.eContents().get(3);
		private final Keyword cCommaKeyword_6_3_0 = (Keyword)cGroup_6_3.eContents().get(0);
		private final Assignment cRoomsAssignment_6_3_1 = (Assignment)cGroup_6_3.eContents().get(1);
		private final RuleCall cRoomsRoomParserRuleCall_6_3_1_0 = (RuleCall)cRoomsAssignment_6_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6_4 = (Keyword)cGroup_6.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//Floor returns Floor:
		//    'Floor'
		//    '{'
		//        'number' number=EInt
		//        'bathrooms' bathrooms=EInt
		//        ('rooms' '{' rooms+=Room ( "," rooms+=Room)* '}' )?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Floor'
		//'{'
		//    'number' number=EInt
		//    'bathrooms' bathrooms=EInt
		//    ('rooms' '{' rooms+=Room ( "," rooms+=Room)* '}' )?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'Floor'
		public Keyword getFloorKeyword_0() { return cFloorKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//'number'
		public Keyword getNumberKeyword_2() { return cNumberKeyword_2; }
		
		//number=EInt
		public Assignment getNumberAssignment_3() { return cNumberAssignment_3; }
		
		//EInt
		public RuleCall getNumberEIntParserRuleCall_3_0() { return cNumberEIntParserRuleCall_3_0; }
		
		//'bathrooms'
		public Keyword getBathroomsKeyword_4() { return cBathroomsKeyword_4; }
		
		//bathrooms=EInt
		public Assignment getBathroomsAssignment_5() { return cBathroomsAssignment_5; }
		
		//EInt
		public RuleCall getBathroomsEIntParserRuleCall_5_0() { return cBathroomsEIntParserRuleCall_5_0; }
		
		//('rooms' '{' rooms+=Room ( "," rooms+=Room)* '}' )?
		public Group getGroup_6() { return cGroup_6; }
		
		//'rooms'
		public Keyword getRoomsKeyword_6_0() { return cRoomsKeyword_6_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_6_1() { return cLeftCurlyBracketKeyword_6_1; }
		
		//rooms+=Room
		public Assignment getRoomsAssignment_6_2() { return cRoomsAssignment_6_2; }
		
		//Room
		public RuleCall getRoomsRoomParserRuleCall_6_2_0() { return cRoomsRoomParserRuleCall_6_2_0; }
		
		//( "," rooms+=Room)*
		public Group getGroup_6_3() { return cGroup_6_3; }
		
		//","
		public Keyword getCommaKeyword_6_3_0() { return cCommaKeyword_6_3_0; }
		
		//rooms+=Room
		public Assignment getRoomsAssignment_6_3_1() { return cRoomsAssignment_6_3_1; }
		
		//Room
		public RuleCall getRoomsRoomParserRuleCall_6_3_1_0() { return cRoomsRoomParserRuleCall_6_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6_4() { return cRightCurlyBracketKeyword_6_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}
	public class EIntElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "it.univaq.disim.unimodel.xtext.Unimodel.EInt");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		
		//EInt returns ecore::EInt:
		//    '-'? INT;
		@Override public ParserRule getRule() { return rule; }
		
		//'-'? INT
		public Group getGroup() { return cGroup; }
		
		//'-'?
		public Keyword getHyphenMinusKeyword_0() { return cHyphenMinusKeyword_0; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_1() { return cINTTerminalRuleCall_1; }
	}
	public class BookElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "it.univaq.disim.unimodel.xtext.Unimodel.Book");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cBookKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cQuantityKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cQuantityAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cQuantityEIntParserRuleCall_4_0 = (RuleCall)cQuantityAssignment_4.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cISBNKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cISBNAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cISBNEStringParserRuleCall_5_1_0 = (RuleCall)cISBNAssignment_5_1.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cAuthorKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cAuthorAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cAuthorEStringParserRuleCall_6_1_0 = (RuleCall)cAuthorAssignment_6_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//Book returns Book:
		//    'Book'
		//    name=EString
		//    '{'
		//        'quantity' quantity=EInt
		//        ('ISBN' ISBN=EString)?
		//        ('author' author=EString)?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Book'
		//name=EString
		//'{'
		//    'quantity' quantity=EInt
		//    ('ISBN' ISBN=EString)?
		//    ('author' author=EString)?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'Book'
		public Keyword getBookKeyword_0() { return cBookKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//'quantity'
		public Keyword getQuantityKeyword_3() { return cQuantityKeyword_3; }
		
		//quantity=EInt
		public Assignment getQuantityAssignment_4() { return cQuantityAssignment_4; }
		
		//EInt
		public RuleCall getQuantityEIntParserRuleCall_4_0() { return cQuantityEIntParserRuleCall_4_0; }
		
		//('ISBN' ISBN=EString)?
		public Group getGroup_5() { return cGroup_5; }
		
		//'ISBN'
		public Keyword getISBNKeyword_5_0() { return cISBNKeyword_5_0; }
		
		//ISBN=EString
		public Assignment getISBNAssignment_5_1() { return cISBNAssignment_5_1; }
		
		//EString
		public RuleCall getISBNEStringParserRuleCall_5_1_0() { return cISBNEStringParserRuleCall_5_1_0; }
		
		//('author' author=EString)?
		public Group getGroup_6() { return cGroup_6; }
		
		//'author'
		public Keyword getAuthorKeyword_6_0() { return cAuthorKeyword_6_0; }
		
		//author=EString
		public Assignment getAuthorAssignment_6_1() { return cAuthorAssignment_6_1; }
		
		//EString
		public RuleCall getAuthorEStringParserRuleCall_6_1_0() { return cAuthorEStringParserRuleCall_6_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}
	public class LoanElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "it.univaq.disim.unimodel.xtext.Unimodel.Loan");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLoanKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cDateKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cDateAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cDateEDateParserRuleCall_3_0 = (RuleCall)cDateAssignment_3.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cBookKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cBookAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final CrossReference cBookBookCrossReference_4_1_0 = (CrossReference)cBookAssignment_4_1.eContents().get(0);
		private final RuleCall cBookBookEStringParserRuleCall_4_1_0_1 = (RuleCall)cBookBookCrossReference_4_1_0.eContents().get(1);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cPersonKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cPersonAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final CrossReference cPersonPersonCrossReference_5_1_0 = (CrossReference)cPersonAssignment_5_1.eContents().get(0);
		private final RuleCall cPersonPersonEStringParserRuleCall_5_1_0_1 = (RuleCall)cPersonPersonCrossReference_5_1_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//Loan returns Loan:
		//    'Loan'
		//    '{'
		//        'date' date=EDate
		//        ('book' book=[Book|EString])?
		//        ('person' person=[Person|EString])?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Loan'
		//'{'
		//    'date' date=EDate
		//    ('book' book=[Book|EString])?
		//    ('person' person=[Person|EString])?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'Loan'
		public Keyword getLoanKeyword_0() { return cLoanKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//'date'
		public Keyword getDateKeyword_2() { return cDateKeyword_2; }
		
		//date=EDate
		public Assignment getDateAssignment_3() { return cDateAssignment_3; }
		
		//EDate
		public RuleCall getDateEDateParserRuleCall_3_0() { return cDateEDateParserRuleCall_3_0; }
		
		//('book' book=[Book|EString])?
		public Group getGroup_4() { return cGroup_4; }
		
		//'book'
		public Keyword getBookKeyword_4_0() { return cBookKeyword_4_0; }
		
		//book=[Book|EString]
		public Assignment getBookAssignment_4_1() { return cBookAssignment_4_1; }
		
		//[Book|EString]
		public CrossReference getBookBookCrossReference_4_1_0() { return cBookBookCrossReference_4_1_0; }
		
		//EString
		public RuleCall getBookBookEStringParserRuleCall_4_1_0_1() { return cBookBookEStringParserRuleCall_4_1_0_1; }
		
		//('person' person=[Person|EString])?
		public Group getGroup_5() { return cGroup_5; }
		
		//'person'
		public Keyword getPersonKeyword_5_0() { return cPersonKeyword_5_0; }
		
		//person=[Person|EString]
		public Assignment getPersonAssignment_5_1() { return cPersonAssignment_5_1; }
		
		//[Person|EString]
		public CrossReference getPersonPersonCrossReference_5_1_0() { return cPersonPersonCrossReference_5_1_0; }
		
		//EString
		public RuleCall getPersonPersonEStringParserRuleCall_5_1_0_1() { return cPersonPersonEStringParserRuleCall_5_1_0_1; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	public class PersonElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "it.univaq.disim.unimodel.xtext.Unimodel.Person");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cPersonKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cCategoryKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cCategoryAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cCategoryCategoryEnumRuleCall_4_0 = (RuleCall)cCategoryAssignment_4.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cBadgeKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cBadgeAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cBadgeEStringParserRuleCall_5_1_0 = (RuleCall)cBadgeAssignment_5_1.eContents().get(0);
		private final Keyword cAgeKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cAgeAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cAgeEIntParserRuleCall_7_0 = (RuleCall)cAgeAssignment_7.eContents().get(0);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cFiscal_codeKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Assignment cFiscal_codeAssignment_8_1 = (Assignment)cGroup_8.eContents().get(1);
		private final RuleCall cFiscal_codeEStringParserRuleCall_8_1_0 = (RuleCall)cFiscal_codeAssignment_8_1.eContents().get(0);
		private final Group cGroup_9 = (Group)cGroup.eContents().get(9);
		private final Keyword cLibraryKeyword_9_0 = (Keyword)cGroup_9.eContents().get(0);
		private final Assignment cLibraryAssignment_9_1 = (Assignment)cGroup_9.eContents().get(1);
		private final CrossReference cLibraryLibraryCrossReference_9_1_0 = (CrossReference)cLibraryAssignment_9_1.eContents().get(0);
		private final RuleCall cLibraryLibraryEStringParserRuleCall_9_1_0_1 = (RuleCall)cLibraryLibraryCrossReference_9_1_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_10 = (Keyword)cGroup.eContents().get(10);
		
		//Person returns Person:
		//    'Person'
		//    name=EString
		//    '{'
		//        'category' category=Category
		//        ('badge' badge=EString)?
		//        'age' age=EInt
		//        ('fiscal_code' fiscal_code=EString)?
		//        ('library' library=[Library|EString])?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Person'
		//name=EString
		//'{'
		//    'category' category=Category
		//    ('badge' badge=EString)?
		//    'age' age=EInt
		//    ('fiscal_code' fiscal_code=EString)?
		//    ('library' library=[Library|EString])?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'Person'
		public Keyword getPersonKeyword_0() { return cPersonKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//'category'
		public Keyword getCategoryKeyword_3() { return cCategoryKeyword_3; }
		
		//category=Category
		public Assignment getCategoryAssignment_4() { return cCategoryAssignment_4; }
		
		//Category
		public RuleCall getCategoryCategoryEnumRuleCall_4_0() { return cCategoryCategoryEnumRuleCall_4_0; }
		
		//('badge' badge=EString)?
		public Group getGroup_5() { return cGroup_5; }
		
		//'badge'
		public Keyword getBadgeKeyword_5_0() { return cBadgeKeyword_5_0; }
		
		//badge=EString
		public Assignment getBadgeAssignment_5_1() { return cBadgeAssignment_5_1; }
		
		//EString
		public RuleCall getBadgeEStringParserRuleCall_5_1_0() { return cBadgeEStringParserRuleCall_5_1_0; }
		
		//'age'
		public Keyword getAgeKeyword_6() { return cAgeKeyword_6; }
		
		//age=EInt
		public Assignment getAgeAssignment_7() { return cAgeAssignment_7; }
		
		//EInt
		public RuleCall getAgeEIntParserRuleCall_7_0() { return cAgeEIntParserRuleCall_7_0; }
		
		//('fiscal_code' fiscal_code=EString)?
		public Group getGroup_8() { return cGroup_8; }
		
		//'fiscal_code'
		public Keyword getFiscal_codeKeyword_8_0() { return cFiscal_codeKeyword_8_0; }
		
		//fiscal_code=EString
		public Assignment getFiscal_codeAssignment_8_1() { return cFiscal_codeAssignment_8_1; }
		
		//EString
		public RuleCall getFiscal_codeEStringParserRuleCall_8_1_0() { return cFiscal_codeEStringParserRuleCall_8_1_0; }
		
		//('library' library=[Library|EString])?
		public Group getGroup_9() { return cGroup_9; }
		
		//'library'
		public Keyword getLibraryKeyword_9_0() { return cLibraryKeyword_9_0; }
		
		//library=[Library|EString]
		public Assignment getLibraryAssignment_9_1() { return cLibraryAssignment_9_1; }
		
		//[Library|EString]
		public CrossReference getLibraryLibraryCrossReference_9_1_0() { return cLibraryLibraryCrossReference_9_1_0; }
		
		//EString
		public RuleCall getLibraryLibraryEStringParserRuleCall_9_1_0_1() { return cLibraryLibraryEStringParserRuleCall_9_1_0_1; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_10() { return cRightCurlyBracketKeyword_10; }
	}
	public class EDateElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "it.univaq.disim.unimodel.xtext.Unimodel.EDate");
		private final Keyword cEDateKeyword = (Keyword)rule.eContents().get(1);
		
		//EDate returns ecore::EDate:
		//    'EDate' /* TODO: implement this rule and an appropriate IValueConverter */;
		@Override public ParserRule getRule() { return rule; }
		
		//'EDate'
		public Keyword getEDateKeyword() { return cEDateKeyword; }
	}
	public class Room_ImplElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "it.univaq.disim.unimodel.xtext.Unimodel.Room_Impl");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cRoomKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cDimensionKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cDimensionAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cDimensionEFloatParserRuleCall_4_0 = (RuleCall)cDimensionAssignment_4.eContents().get(0);
		private final Keyword cSocketsKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cSocketsAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cSocketsEIntParserRuleCall_6_0 = (RuleCall)cSocketsAssignment_6.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//Room_Impl returns Room:
		//    'Room'
		//    name=EString
		//    '{'
		//        'dimension' dimension=EFloat
		//        'sockets' sockets=EInt
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Room'
		//name=EString
		//'{'
		//    'dimension' dimension=EFloat
		//    'sockets' sockets=EInt
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'Room'
		public Keyword getRoomKeyword_0() { return cRoomKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//'dimension'
		public Keyword getDimensionKeyword_3() { return cDimensionKeyword_3; }
		
		//dimension=EFloat
		public Assignment getDimensionAssignment_4() { return cDimensionAssignment_4; }
		
		//EFloat
		public RuleCall getDimensionEFloatParserRuleCall_4_0() { return cDimensionEFloatParserRuleCall_4_0; }
		
		//'sockets'
		public Keyword getSocketsKeyword_5() { return cSocketsKeyword_5; }
		
		//sockets=EInt
		public Assignment getSocketsAssignment_6() { return cSocketsAssignment_6; }
		
		//EInt
		public RuleCall getSocketsEIntParserRuleCall_6_0() { return cSocketsEIntParserRuleCall_6_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}
	public class EFloatElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "it.univaq.disim.unimodel.xtext.Unimodel.EFloat");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		private final Keyword cFullStopKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final RuleCall cINTTerminalRuleCall_3 = (RuleCall)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Alternatives cAlternatives_4_0 = (Alternatives)cGroup_4.eContents().get(0);
		private final Keyword cEKeyword_4_0_0 = (Keyword)cAlternatives_4_0.eContents().get(0);
		private final Keyword cEKeyword_4_0_1 = (Keyword)cAlternatives_4_0.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final RuleCall cINTTerminalRuleCall_4_2 = (RuleCall)cGroup_4.eContents().get(2);
		
		//EFloat returns ecore::EFloat:
		//    '-'? INT? '.' INT (('E'|'e') '-'? INT)?;
		@Override public ParserRule getRule() { return rule; }
		
		//'-'? INT? '.' INT (('E'|'e') '-'? INT)?
		public Group getGroup() { return cGroup; }
		
		//'-'?
		public Keyword getHyphenMinusKeyword_0() { return cHyphenMinusKeyword_0; }
		
		//INT?
		public RuleCall getINTTerminalRuleCall_1() { return cINTTerminalRuleCall_1; }
		
		//'.'
		public Keyword getFullStopKeyword_2() { return cFullStopKeyword_2; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_3() { return cINTTerminalRuleCall_3; }
		
		//(('E'|'e') '-'? INT)?
		public Group getGroup_4() { return cGroup_4; }
		
		//('E'|'e')
		public Alternatives getAlternatives_4_0() { return cAlternatives_4_0; }
		
		//'E'
		public Keyword getEKeyword_4_0_0() { return cEKeyword_4_0_0; }
		
		//'e'
		public Keyword getEKeyword_4_0_1() { return cEKeyword_4_0_1; }
		
		//'-'?
		public Keyword getHyphenMinusKeyword_4_1() { return cHyphenMinusKeyword_4_1; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_4_2() { return cINTTerminalRuleCall_4_2; }
	}
	public class OfficeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "it.univaq.disim.unimodel.xtext.Unimodel.Office");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cOfficeKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cDimensionKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cDimensionAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cDimensionEFloatParserRuleCall_4_0 = (RuleCall)cDimensionAssignment_4.eContents().get(0);
		private final Keyword cSocketsKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cSocketsAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cSocketsEIntParserRuleCall_6_0 = (RuleCall)cSocketsAssignment_6.eContents().get(0);
		private final Keyword cTypeKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cTypeAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cTypeTypeEnumRuleCall_8_0 = (RuleCall)cTypeAssignment_8.eContents().get(0);
		private final Keyword cCapacityKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Assignment cCapacityAssignment_10 = (Assignment)cGroup.eContents().get(10);
		private final RuleCall cCapacityEIntParserRuleCall_10_0 = (RuleCall)cCapacityAssignment_10.eContents().get(0);
		private final Group cGroup_11 = (Group)cGroup.eContents().get(11);
		private final Keyword cPhoneKeyword_11_0 = (Keyword)cGroup_11.eContents().get(0);
		private final Assignment cPhoneAssignment_11_1 = (Assignment)cGroup_11.eContents().get(1);
		private final RuleCall cPhoneEStringParserRuleCall_11_1_0 = (RuleCall)cPhoneAssignment_11_1.eContents().get(0);
		private final Keyword cOffice_addressKeyword_12 = (Keyword)cGroup.eContents().get(12);
		private final Assignment cOffice_addressAssignment_13 = (Assignment)cGroup.eContents().get(13);
		private final CrossReference cOffice_addressAddressCrossReference_13_0 = (CrossReference)cOffice_addressAssignment_13.eContents().get(0);
		private final RuleCall cOffice_addressAddressEStringParserRuleCall_13_0_1 = (RuleCall)cOffice_addressAddressCrossReference_13_0.eContents().get(1);
		private final Keyword cPerson_in_officeKeyword_14 = (Keyword)cGroup.eContents().get(14);
		private final Keyword cLeftCurlyBracketKeyword_15 = (Keyword)cGroup.eContents().get(15);
		private final Assignment cPerson_in_officeAssignment_16 = (Assignment)cGroup.eContents().get(16);
		private final RuleCall cPerson_in_officePersonParserRuleCall_16_0 = (RuleCall)cPerson_in_officeAssignment_16.eContents().get(0);
		private final Group cGroup_17 = (Group)cGroup.eContents().get(17);
		private final Keyword cCommaKeyword_17_0 = (Keyword)cGroup_17.eContents().get(0);
		private final Assignment cPerson_in_officeAssignment_17_1 = (Assignment)cGroup_17.eContents().get(1);
		private final RuleCall cPerson_in_officePersonParserRuleCall_17_1_0 = (RuleCall)cPerson_in_officeAssignment_17_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_18 = (Keyword)cGroup.eContents().get(18);
		private final Keyword cRightCurlyBracketKeyword_19 = (Keyword)cGroup.eContents().get(19);
		
		//Office returns Office:
		//    'Office'
		//    name=EString
		//    '{'
		//        'dimension' dimension=EFloat
		//        'sockets' sockets=EInt
		//        'type' type=Type
		//        'capacity' capacity=EInt
		//        ('phone' phone=EString)?
		//        'office_address' office_address=[Address|EString]
		//        'person_in_office' '{' person_in_office+=Person ( "," person_in_office+=Person)* '}'
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Office'
		//name=EString
		//'{'
		//    'dimension' dimension=EFloat
		//    'sockets' sockets=EInt
		//    'type' type=Type
		//    'capacity' capacity=EInt
		//    ('phone' phone=EString)?
		//    'office_address' office_address=[Address|EString]
		//    'person_in_office' '{' person_in_office+=Person ( "," person_in_office+=Person)* '}'
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'Office'
		public Keyword getOfficeKeyword_0() { return cOfficeKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//'dimension'
		public Keyword getDimensionKeyword_3() { return cDimensionKeyword_3; }
		
		//dimension=EFloat
		public Assignment getDimensionAssignment_4() { return cDimensionAssignment_4; }
		
		//EFloat
		public RuleCall getDimensionEFloatParserRuleCall_4_0() { return cDimensionEFloatParserRuleCall_4_0; }
		
		//'sockets'
		public Keyword getSocketsKeyword_5() { return cSocketsKeyword_5; }
		
		//sockets=EInt
		public Assignment getSocketsAssignment_6() { return cSocketsAssignment_6; }
		
		//EInt
		public RuleCall getSocketsEIntParserRuleCall_6_0() { return cSocketsEIntParserRuleCall_6_0; }
		
		//'type'
		public Keyword getTypeKeyword_7() { return cTypeKeyword_7; }
		
		//type=Type
		public Assignment getTypeAssignment_8() { return cTypeAssignment_8; }
		
		//Type
		public RuleCall getTypeTypeEnumRuleCall_8_0() { return cTypeTypeEnumRuleCall_8_0; }
		
		//'capacity'
		public Keyword getCapacityKeyword_9() { return cCapacityKeyword_9; }
		
		//capacity=EInt
		public Assignment getCapacityAssignment_10() { return cCapacityAssignment_10; }
		
		//EInt
		public RuleCall getCapacityEIntParserRuleCall_10_0() { return cCapacityEIntParserRuleCall_10_0; }
		
		//('phone' phone=EString)?
		public Group getGroup_11() { return cGroup_11; }
		
		//'phone'
		public Keyword getPhoneKeyword_11_0() { return cPhoneKeyword_11_0; }
		
		//phone=EString
		public Assignment getPhoneAssignment_11_1() { return cPhoneAssignment_11_1; }
		
		//EString
		public RuleCall getPhoneEStringParserRuleCall_11_1_0() { return cPhoneEStringParserRuleCall_11_1_0; }
		
		//'office_address'
		public Keyword getOffice_addressKeyword_12() { return cOffice_addressKeyword_12; }
		
		//office_address=[Address|EString]
		public Assignment getOffice_addressAssignment_13() { return cOffice_addressAssignment_13; }
		
		//[Address|EString]
		public CrossReference getOffice_addressAddressCrossReference_13_0() { return cOffice_addressAddressCrossReference_13_0; }
		
		//EString
		public RuleCall getOffice_addressAddressEStringParserRuleCall_13_0_1() { return cOffice_addressAddressEStringParserRuleCall_13_0_1; }
		
		//'person_in_office'
		public Keyword getPerson_in_officeKeyword_14() { return cPerson_in_officeKeyword_14; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_15() { return cLeftCurlyBracketKeyword_15; }
		
		//person_in_office+=Person
		public Assignment getPerson_in_officeAssignment_16() { return cPerson_in_officeAssignment_16; }
		
		//Person
		public RuleCall getPerson_in_officePersonParserRuleCall_16_0() { return cPerson_in_officePersonParserRuleCall_16_0; }
		
		//( "," person_in_office+=Person)*
		public Group getGroup_17() { return cGroup_17; }
		
		//","
		public Keyword getCommaKeyword_17_0() { return cCommaKeyword_17_0; }
		
		//person_in_office+=Person
		public Assignment getPerson_in_officeAssignment_17_1() { return cPerson_in_officeAssignment_17_1; }
		
		//Person
		public RuleCall getPerson_in_officePersonParserRuleCall_17_1_0() { return cPerson_in_officePersonParserRuleCall_17_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_18() { return cRightCurlyBracketKeyword_18; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_19() { return cRightCurlyBracketKeyword_19; }
	}
	public class ClassElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "it.univaq.disim.unimodel.xtext.Unimodel.Class");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cClassKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cDimensionKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cDimensionAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cDimensionEFloatParserRuleCall_4_0 = (RuleCall)cDimensionAssignment_4.eContents().get(0);
		private final Keyword cSocketsKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cSocketsAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cSocketsEIntParserRuleCall_6_0 = (RuleCall)cSocketsAssignment_6.eContents().get(0);
		private final Keyword cSeatsKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cSeatsAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cSeatsEIntParserRuleCall_8_0 = (RuleCall)cSeatsAssignment_8.eContents().get(0);
		private final Keyword cBlackboardsKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Assignment cBlackboardsAssignment_10 = (Assignment)cGroup.eContents().get(10);
		private final RuleCall cBlackboardsEIntParserRuleCall_10_0 = (RuleCall)cBlackboardsAssignment_10.eContents().get(0);
		private final Keyword cSpeakersKeyword_11 = (Keyword)cGroup.eContents().get(11);
		private final Assignment cSpeakersAssignment_12 = (Assignment)cGroup.eContents().get(12);
		private final RuleCall cSpeakersEIntParserRuleCall_12_0 = (RuleCall)cSpeakersAssignment_12.eContents().get(0);
		private final Keyword cComputersKeyword_13 = (Keyword)cGroup.eContents().get(13);
		private final Assignment cComputersAssignment_14 = (Assignment)cGroup.eContents().get(14);
		private final RuleCall cComputersEIntParserRuleCall_14_0 = (RuleCall)cComputersAssignment_14.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_15 = (Keyword)cGroup.eContents().get(15);
		
		//Class returns Class:
		//    'Class'
		//    name=EString
		//    '{'
		//        'dimension' dimension=EFloat
		//        'sockets' sockets=EInt
		//        'seats' seats=EInt
		//        'blackboards' blackboards=EInt
		//        'speakers' speakers=EInt
		//        'computers' computers=EInt
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Class'
		//name=EString
		//'{'
		//    'dimension' dimension=EFloat
		//    'sockets' sockets=EInt
		//    'seats' seats=EInt
		//    'blackboards' blackboards=EInt
		//    'speakers' speakers=EInt
		//    'computers' computers=EInt
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'Class'
		public Keyword getClassKeyword_0() { return cClassKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//'dimension'
		public Keyword getDimensionKeyword_3() { return cDimensionKeyword_3; }
		
		//dimension=EFloat
		public Assignment getDimensionAssignment_4() { return cDimensionAssignment_4; }
		
		//EFloat
		public RuleCall getDimensionEFloatParserRuleCall_4_0() { return cDimensionEFloatParserRuleCall_4_0; }
		
		//'sockets'
		public Keyword getSocketsKeyword_5() { return cSocketsKeyword_5; }
		
		//sockets=EInt
		public Assignment getSocketsAssignment_6() { return cSocketsAssignment_6; }
		
		//EInt
		public RuleCall getSocketsEIntParserRuleCall_6_0() { return cSocketsEIntParserRuleCall_6_0; }
		
		//'seats'
		public Keyword getSeatsKeyword_7() { return cSeatsKeyword_7; }
		
		//seats=EInt
		public Assignment getSeatsAssignment_8() { return cSeatsAssignment_8; }
		
		//EInt
		public RuleCall getSeatsEIntParserRuleCall_8_0() { return cSeatsEIntParserRuleCall_8_0; }
		
		//'blackboards'
		public Keyword getBlackboardsKeyword_9() { return cBlackboardsKeyword_9; }
		
		//blackboards=EInt
		public Assignment getBlackboardsAssignment_10() { return cBlackboardsAssignment_10; }
		
		//EInt
		public RuleCall getBlackboardsEIntParserRuleCall_10_0() { return cBlackboardsEIntParserRuleCall_10_0; }
		
		//'speakers'
		public Keyword getSpeakersKeyword_11() { return cSpeakersKeyword_11; }
		
		//speakers=EInt
		public Assignment getSpeakersAssignment_12() { return cSpeakersAssignment_12; }
		
		//EInt
		public RuleCall getSpeakersEIntParserRuleCall_12_0() { return cSpeakersEIntParserRuleCall_12_0; }
		
		//'computers'
		public Keyword getComputersKeyword_13() { return cComputersKeyword_13; }
		
		//computers=EInt
		public Assignment getComputersAssignment_14() { return cComputersAssignment_14; }
		
		//EInt
		public RuleCall getComputersEIntParserRuleCall_14_0() { return cComputersEIntParserRuleCall_14_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_15() { return cRightCurlyBracketKeyword_15; }
	}
	
	public class CategoryElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "it.univaq.disim.unimodel.xtext.Unimodel.Category");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cPROFESSOREnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cPROFESSORPROFESSORKeyword_0_0 = (Keyword)cPROFESSOREnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cPHD_STUDENTEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cPHD_STUDENTPHD_STUDENTKeyword_1_0 = (Keyword)cPHD_STUDENTEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cADMINISTRATOREnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cADMINISTRATORADMINISTRATORKeyword_2_0 = (Keyword)cADMINISTRATOREnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cSTAFFEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cSTAFFSTAFFKeyword_3_0 = (Keyword)cSTAFFEnumLiteralDeclaration_3.eContents().get(0);
		private final EnumLiteralDeclaration cSTUDENTEnumLiteralDeclaration_4 = (EnumLiteralDeclaration)cAlternatives.eContents().get(4);
		private final Keyword cSTUDENTSTUDENTKeyword_4_0 = (Keyword)cSTUDENTEnumLiteralDeclaration_4.eContents().get(0);
		
		//enum Category returns Category:
		//                PROFESSOR = 'PROFESSOR' | PHD_STUDENT = 'PHD_STUDENT' | ADMINISTRATOR = 'ADMINISTRATOR' | STAFF = 'STAFF' | STUDENT = 'STUDENT';
		public EnumRule getRule() { return rule; }
		
		//PROFESSOR = 'PROFESSOR' | PHD_STUDENT = 'PHD_STUDENT' | ADMINISTRATOR = 'ADMINISTRATOR' | STAFF = 'STAFF' | STUDENT = 'STUDENT'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//PROFESSOR = 'PROFESSOR'
		public EnumLiteralDeclaration getPROFESSOREnumLiteralDeclaration_0() { return cPROFESSOREnumLiteralDeclaration_0; }
		
		//'PROFESSOR'
		public Keyword getPROFESSORPROFESSORKeyword_0_0() { return cPROFESSORPROFESSORKeyword_0_0; }
		
		//PHD_STUDENT = 'PHD_STUDENT'
		public EnumLiteralDeclaration getPHD_STUDENTEnumLiteralDeclaration_1() { return cPHD_STUDENTEnumLiteralDeclaration_1; }
		
		//'PHD_STUDENT'
		public Keyword getPHD_STUDENTPHD_STUDENTKeyword_1_0() { return cPHD_STUDENTPHD_STUDENTKeyword_1_0; }
		
		//ADMINISTRATOR = 'ADMINISTRATOR'
		public EnumLiteralDeclaration getADMINISTRATOREnumLiteralDeclaration_2() { return cADMINISTRATOREnumLiteralDeclaration_2; }
		
		//'ADMINISTRATOR'
		public Keyword getADMINISTRATORADMINISTRATORKeyword_2_0() { return cADMINISTRATORADMINISTRATORKeyword_2_0; }
		
		//STAFF = 'STAFF'
		public EnumLiteralDeclaration getSTAFFEnumLiteralDeclaration_3() { return cSTAFFEnumLiteralDeclaration_3; }
		
		//'STAFF'
		public Keyword getSTAFFSTAFFKeyword_3_0() { return cSTAFFSTAFFKeyword_3_0; }
		
		//STUDENT = 'STUDENT'
		public EnumLiteralDeclaration getSTUDENTEnumLiteralDeclaration_4() { return cSTUDENTEnumLiteralDeclaration_4; }
		
		//'STUDENT'
		public Keyword getSTUDENTSTUDENTKeyword_4_0() { return cSTUDENTSTUDENTKeyword_4_0; }
	}
	public class TypeElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "it.univaq.disim.unimodel.xtext.Unimodel.Type");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cPROFESSOR_OFFICEEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cPROFESSOR_OFFICEPROFESSOR_OFFICEKeyword_0_0 = (Keyword)cPROFESSOR_OFFICEEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cPHD_ROOMEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cPHD_ROOMPHD_ROOMKeyword_1_0 = (Keyword)cPHD_ROOMEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cADMINISTRATIONEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cADMINISTRATIONADMINISTRATIONKeyword_2_0 = (Keyword)cADMINISTRATIONEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cSECRETARIATEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cSECRETARIATSECRETARIATKeyword_3_0 = (Keyword)cSECRETARIATEnumLiteralDeclaration_3.eContents().get(0);
		
		//enum Type returns Type:
		//                PROFESSOR_OFFICE = 'PROFESSOR_OFFICE' | PHD_ROOM = 'PHD_ROOM' | ADMINISTRATION = 'ADMINISTRATION' | SECRETARIAT = 'SECRETARIAT';
		public EnumRule getRule() { return rule; }
		
		//PROFESSOR_OFFICE = 'PROFESSOR_OFFICE' | PHD_ROOM = 'PHD_ROOM' | ADMINISTRATION = 'ADMINISTRATION' | SECRETARIAT = 'SECRETARIAT'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//PROFESSOR_OFFICE = 'PROFESSOR_OFFICE'
		public EnumLiteralDeclaration getPROFESSOR_OFFICEEnumLiteralDeclaration_0() { return cPROFESSOR_OFFICEEnumLiteralDeclaration_0; }
		
		//'PROFESSOR_OFFICE'
		public Keyword getPROFESSOR_OFFICEPROFESSOR_OFFICEKeyword_0_0() { return cPROFESSOR_OFFICEPROFESSOR_OFFICEKeyword_0_0; }
		
		//PHD_ROOM = 'PHD_ROOM'
		public EnumLiteralDeclaration getPHD_ROOMEnumLiteralDeclaration_1() { return cPHD_ROOMEnumLiteralDeclaration_1; }
		
		//'PHD_ROOM'
		public Keyword getPHD_ROOMPHD_ROOMKeyword_1_0() { return cPHD_ROOMPHD_ROOMKeyword_1_0; }
		
		//ADMINISTRATION = 'ADMINISTRATION'
		public EnumLiteralDeclaration getADMINISTRATIONEnumLiteralDeclaration_2() { return cADMINISTRATIONEnumLiteralDeclaration_2; }
		
		//'ADMINISTRATION'
		public Keyword getADMINISTRATIONADMINISTRATIONKeyword_2_0() { return cADMINISTRATIONADMINISTRATIONKeyword_2_0; }
		
		//SECRETARIAT = 'SECRETARIAT'
		public EnumLiteralDeclaration getSECRETARIATEnumLiteralDeclaration_3() { return cSECRETARIATEnumLiteralDeclaration_3; }
		
		//'SECRETARIAT'
		public Keyword getSECRETARIATSECRETARIATKeyword_3_0() { return cSECRETARIATSECRETARIATKeyword_3_0; }
	}
	
	private final UniversityElements pUniversity;
	private final RoomElements pRoom;
	private final EStringElements pEString;
	private final BuildingElements pBuilding;
	private final AddressElements pAddress;
	private final LibraryElements pLibrary;
	private final FloorElements pFloor;
	private final EIntElements pEInt;
	private final BookElements pBook;
	private final LoanElements pLoan;
	private final PersonElements pPerson;
	private final EDateElements pEDate;
	private final CategoryElements eCategory;
	private final Room_ImplElements pRoom_Impl;
	private final EFloatElements pEFloat;
	private final OfficeElements pOffice;
	private final ClassElements pClass;
	private final TypeElements eType;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public UnimodelGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pUniversity = new UniversityElements();
		this.pRoom = new RoomElements();
		this.pEString = new EStringElements();
		this.pBuilding = new BuildingElements();
		this.pAddress = new AddressElements();
		this.pLibrary = new LibraryElements();
		this.pFloor = new FloorElements();
		this.pEInt = new EIntElements();
		this.pBook = new BookElements();
		this.pLoan = new LoanElements();
		this.pPerson = new PersonElements();
		this.pEDate = new EDateElements();
		this.eCategory = new CategoryElements();
		this.pRoom_Impl = new Room_ImplElements();
		this.pEFloat = new EFloatElements();
		this.pOffice = new OfficeElements();
		this.pClass = new ClassElements();
		this.eType = new TypeElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("it.univaq.disim.unimodel.xtext.Unimodel".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//University returns University:
	//    'University'
	//    name=EString
	//    '{'
	//        ('chancellor' chancellor=EString)?
	//        ('description' description=EString)?
	//        'buildings' '{' buildings+=Building ( "," buildings+=Building)* '}'
	//    '}';
	public UniversityElements getUniversityAccess() {
		return pUniversity;
	}
	
	public ParserRule getUniversityRule() {
		return getUniversityAccess().getRule();
	}
	
	//Room returns Room:
	//    Room_Impl | Office | Class;
	public RoomElements getRoomAccess() {
		return pRoom;
	}
	
	public ParserRule getRoomRule() {
		return getRoomAccess().getRule();
	}
	
	//EString returns ecore::EString:
	//    STRING | ID;
	public EStringElements getEStringAccess() {
		return pEString;
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}
	
	//Building returns Building:
	//    'Building'
	//    name=EString
	//    '{'
	//        ('description' description=EString)?
	//        'address' address=Address
	//        ('library' library=Library)?
	//        'floors' '{' floors+=Floor ( "," floors+=Floor)* '}'
	//    '}';
	public BuildingElements getBuildingAccess() {
		return pBuilding;
	}
	
	public ParserRule getBuildingRule() {
		return getBuildingAccess().getRule();
	}
	
	//Address returns Address:
	//    {Address}
	//    'Address'
	//    id=EInt
	//    '{'
	//        ('country' country=EString)?
	//        ('state' state=EString)?
	//        ('city' city=EString)?
	//        ('post_code' post_code=EString)?
	//        ('street' street=EString)?
	//        ('civic' civic=EString)?
	//        ('phone' phone=EString)?
	//    '}';
	public AddressElements getAddressAccess() {
		return pAddress;
	}
	
	public ParserRule getAddressRule() {
		return getAddressAccess().getRule();
	}
	
	//Library returns Library:
	//    'Library'
	//    name=EString
	//    '{'
	//        'workstations' workstations=EInt
	//        'computers' computers=EInt
	//        ('books' '{' books+=Book ( "," books+=Book)* '}' )?
	//        ('loans' '{' loans+=Loan ( "," loans+=Loan)* '}' )?
	//        ('person' '{' person+=Person ( "," person+=Person)* '}' )?
	//    '}';
	public LibraryElements getLibraryAccess() {
		return pLibrary;
	}
	
	public ParserRule getLibraryRule() {
		return getLibraryAccess().getRule();
	}
	
	//Floor returns Floor:
	//    'Floor'
	//    '{'
	//        'number' number=EInt
	//        'bathrooms' bathrooms=EInt
	//        ('rooms' '{' rooms+=Room ( "," rooms+=Room)* '}' )?
	//    '}';
	public FloorElements getFloorAccess() {
		return pFloor;
	}
	
	public ParserRule getFloorRule() {
		return getFloorAccess().getRule();
	}
	
	//EInt returns ecore::EInt:
	//    '-'? INT;
	public EIntElements getEIntAccess() {
		return pEInt;
	}
	
	public ParserRule getEIntRule() {
		return getEIntAccess().getRule();
	}
	
	//Book returns Book:
	//    'Book'
	//    name=EString
	//    '{'
	//        'quantity' quantity=EInt
	//        ('ISBN' ISBN=EString)?
	//        ('author' author=EString)?
	//    '}';
	public BookElements getBookAccess() {
		return pBook;
	}
	
	public ParserRule getBookRule() {
		return getBookAccess().getRule();
	}
	
	//Loan returns Loan:
	//    'Loan'
	//    '{'
	//        'date' date=EDate
	//        ('book' book=[Book|EString])?
	//        ('person' person=[Person|EString])?
	//    '}';
	public LoanElements getLoanAccess() {
		return pLoan;
	}
	
	public ParserRule getLoanRule() {
		return getLoanAccess().getRule();
	}
	
	//Person returns Person:
	//    'Person'
	//    name=EString
	//    '{'
	//        'category' category=Category
	//        ('badge' badge=EString)?
	//        'age' age=EInt
	//        ('fiscal_code' fiscal_code=EString)?
	//        ('library' library=[Library|EString])?
	//    '}';
	public PersonElements getPersonAccess() {
		return pPerson;
	}
	
	public ParserRule getPersonRule() {
		return getPersonAccess().getRule();
	}
	
	//EDate returns ecore::EDate:
	//    'EDate' /* TODO: implement this rule and an appropriate IValueConverter */;
	public EDateElements getEDateAccess() {
		return pEDate;
	}
	
	public ParserRule getEDateRule() {
		return getEDateAccess().getRule();
	}
	
	//enum Category returns Category:
	//                PROFESSOR = 'PROFESSOR' | PHD_STUDENT = 'PHD_STUDENT' | ADMINISTRATOR = 'ADMINISTRATOR' | STAFF = 'STAFF' | STUDENT = 'STUDENT';
	public CategoryElements getCategoryAccess() {
		return eCategory;
	}
	
	public EnumRule getCategoryRule() {
		return getCategoryAccess().getRule();
	}
	
	//Room_Impl returns Room:
	//    'Room'
	//    name=EString
	//    '{'
	//        'dimension' dimension=EFloat
	//        'sockets' sockets=EInt
	//    '}';
	public Room_ImplElements getRoom_ImplAccess() {
		return pRoom_Impl;
	}
	
	public ParserRule getRoom_ImplRule() {
		return getRoom_ImplAccess().getRule();
	}
	
	//EFloat returns ecore::EFloat:
	//    '-'? INT? '.' INT (('E'|'e') '-'? INT)?;
	public EFloatElements getEFloatAccess() {
		return pEFloat;
	}
	
	public ParserRule getEFloatRule() {
		return getEFloatAccess().getRule();
	}
	
	//Office returns Office:
	//    'Office'
	//    name=EString
	//    '{'
	//        'dimension' dimension=EFloat
	//        'sockets' sockets=EInt
	//        'type' type=Type
	//        'capacity' capacity=EInt
	//        ('phone' phone=EString)?
	//        'office_address' office_address=[Address|EString]
	//        'person_in_office' '{' person_in_office+=Person ( "," person_in_office+=Person)* '}'
	//    '}';
	public OfficeElements getOfficeAccess() {
		return pOffice;
	}
	
	public ParserRule getOfficeRule() {
		return getOfficeAccess().getRule();
	}
	
	//Class returns Class:
	//    'Class'
	//    name=EString
	//    '{'
	//        'dimension' dimension=EFloat
	//        'sockets' sockets=EInt
	//        'seats' seats=EInt
	//        'blackboards' blackboards=EInt
	//        'speakers' speakers=EInt
	//        'computers' computers=EInt
	//    '}';
	public ClassElements getClassAccess() {
		return pClass;
	}
	
	public ParserRule getClassRule() {
		return getClassAccess().getRule();
	}
	
	//enum Type returns Type:
	//                PROFESSOR_OFFICE = 'PROFESSOR_OFFICE' | PHD_ROOM = 'PHD_ROOM' | ADMINISTRATION = 'ADMINISTRATION' | SECRETARIAT = 'SECRETARIAT';
	public TypeElements getTypeAccess() {
		return eType;
	}
	
	public EnumRule getTypeRule() {
		return getTypeAccess().getRule();
	}
	
	//terminal ID: '^'?('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt: ('0'..'9')+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//            '"' ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|'"') )* '"' |
	//            "'" ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|"'") )* "'"
	//        ;
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT : '/*' -> '*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT : '//' !('\n'|'\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS         : (' '|'\t'|'\r'|'\n')+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER: .;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
