/*
 * generated by Xtext 2.25.0
 */
package it.univaq.disim.unimodel.xtext.ui.contentassist


/**
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#content-assist
 * on how to customize the content assistant.
 */
class UnimodelProposalProvider extends AbstractUnimodelProposalProvider {
}
