/**
 * generated by Xtext 2.25.0
 */
package it.univaq.disim.unimodel.xtext.validation;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class UnimodelValidator extends AbstractUnimodelValidator {
}
