/*
 * generated by Xtext 2.25.0
 */
package it.univaq.disim.unimodel.xtext.parser.antlr;

import com.google.inject.Inject;
import it.univaq.disim.unimodel.xtext.parser.antlr.internal.InternalUnimodelParser;
import it.univaq.disim.unimodel.xtext.services.UnimodelGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class UnimodelParser extends AbstractAntlrParser {

	@Inject
	private UnimodelGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalUnimodelParser createParser(XtextTokenStream stream) {
		return new InternalUnimodelParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "University";
	}

	public UnimodelGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(UnimodelGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
