/*
 * generated by Xtext 2.25.0
 */
package it.univaq.disim.unimodel.xtext.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractUnimodelScopeProvider extends DelegatingScopeProvider {
}
