/**
 * generated by Xtext 2.25.0
 */
package it.univaq.disim.unimodel.xtext;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class UnimodelStandaloneSetup extends UnimodelStandaloneSetupGenerated {
  public static void doSetup() {
    new UnimodelStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
