/**
 * generated by Xtext 2.25.0
 */
package it.univaq.disim.unimodel.xtext.ide;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class UnimodelIdeModule extends AbstractUnimodelIdeModule {
}
