package unimodel.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.smodel.runtime.ConstrainedStringDatatypeDescriptor;
import jetbrains.mps.smodel.runtime.ConstrainedStringDatatypeDescriptorImpl;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import jetbrains.mps.smodel.runtime.DataTypeDescriptor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptAddress = createDescriptorForAddress();
  /*package*/ final ConceptDescriptor myConceptBook = createDescriptorForBook();
  /*package*/ final ConceptDescriptor myConceptBuilding = createDescriptorForBuilding();
  /*package*/ final ConceptDescriptor myConceptClass = createDescriptorForClass();
  /*package*/ final ConceptDescriptor myConceptFloor = createDescriptorForFloor();
  /*package*/ final ConceptDescriptor myConceptLibrary = createDescriptorForLibrary();
  /*package*/ final ConceptDescriptor myConceptLoans = createDescriptorForLoans();
  /*package*/ final ConceptDescriptor myConceptOffice = createDescriptorForOffice();
  /*package*/ final ConceptDescriptor myConceptPerson = createDescriptorForPerson();
  /*package*/ final ConceptDescriptor myConceptRoom = createDescriptorForRoom();
  /*package*/ final ConceptDescriptor myConceptUniversity = createDescriptorForUniversity();
  /*package*/ final EnumerationDescriptor myEnumerationCategory = new EnumerationDescriptor_Category();
  /*package*/ final EnumerationDescriptor myEnumerationType = new EnumerationDescriptor_Type();
  /*package*/ final ConstrainedStringDatatypeDescriptor myCSDatatypedate = new ConstrainedStringDatatypeDescriptorImpl(0x6069f38ad5c2473eL, 0xbe656672ae45792cL, 0x79555ffcb891b58eL, "date", "r:8a1ac2af-b452-4f6d-a997-fcde45094820(unimodel.structure)/8742999790642640270", "^([0]?[1-9]|[1|2][0-9]|[3][0|1])[./-]([0]?[1-9]|[1][0-2])[./-]([0-9]{4}|[0-9]{2})$");
  /*package*/ final ConstrainedStringDatatypeDescriptor myCSDatatypefloat = new ConstrainedStringDatatypeDescriptorImpl(0x6069f38ad5c2473eL, 0xbe656672ae45792cL, 0x79555ffcb891b597L, "float", "r:8a1ac2af-b452-4f6d-a997-fcde45094820(unimodel.structure)/8742999790642640279", "^[0-9]+\\.[0-9]+$");
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptAddress, myConceptBook, myConceptBuilding, myConceptClass, myConceptFloor, myConceptLibrary, myConceptLoans, myConceptOffice, myConceptPerson, myConceptRoom, myConceptUniversity);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.Address:
        return myConceptAddress;
      case LanguageConceptSwitch.Book:
        return myConceptBook;
      case LanguageConceptSwitch.Building:
        return myConceptBuilding;
      case LanguageConceptSwitch.Class:
        return myConceptClass;
      case LanguageConceptSwitch.Floor:
        return myConceptFloor;
      case LanguageConceptSwitch.Library:
        return myConceptLibrary;
      case LanguageConceptSwitch.Loans:
        return myConceptLoans;
      case LanguageConceptSwitch.Office:
        return myConceptOffice;
      case LanguageConceptSwitch.Person:
        return myConceptPerson;
      case LanguageConceptSwitch.Room:
        return myConceptRoom;
      case LanguageConceptSwitch.University:
        return myConceptUniversity;
      default:
        return null;
    }
  }

  @Override
  public Collection<DataTypeDescriptor> getDataTypeDescriptors() {
    return Arrays.asList(myEnumerationCategory, myEnumerationType, myCSDatatypedate, myCSDatatypefloat);
  }

  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForAddress() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("unimodel", "Address", 0x6069f38ad5c2473eL, 0xbe656672ae45792cL, 0x79555ffcb891b538L);
    b.class_(false, false, false);
    b.origin("r:8a1ac2af-b452-4f6d-a997-fcde45094820(unimodel.structure)/8742999790642640184");
    b.version(2);
    b.property("id", 0x79555ffcb891b8e6L).type(PrimitiveTypeId.INTEGER).origin("8742999790642641126").done();
    b.property("country", 0x79555ffcb891b53cL).type(PrimitiveTypeId.STRING).origin("8742999790642640188").done();
    b.property("state", 0x79555ffcb891b53eL).type(PrimitiveTypeId.STRING).origin("8742999790642640190").done();
    b.property("city", 0x79555ffcb891b541L).type(PrimitiveTypeId.STRING).origin("8742999790642640193").done();
    b.property("post_code", 0x79555ffcb891b545L).type(PrimitiveTypeId.STRING).origin("8742999790642640197").done();
    b.property("street", 0x79555ffcb891b54aL).type(PrimitiveTypeId.STRING).origin("8742999790642640202").done();
    b.property("civic", 0x79555ffcb891b550L).type(PrimitiveTypeId.STRING).origin("8742999790642640208").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForBook() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("unimodel", "Book", 0x6069f38ad5c2473eL, 0xbe656672ae45792cL, 0x79555ffcb891b57fL);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:8a1ac2af-b452-4f6d-a997-fcde45094820(unimodel.structure)/8742999790642640255");
    b.version(2);
    b.property("quantity", 0x79555ffcb891b582L).type(PrimitiveTypeId.INTEGER).origin("8742999790642640258").done();
    b.property("ISBN", 0x79555ffcb891b584L).type(PrimitiveTypeId.STRING).origin("8742999790642640260").done();
    b.property("authors", 0x79555ffcb891b587L).type(PrimitiveTypeId.STRING).origin("8742999790642640263").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForBuilding() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("unimodel", "Building", 0x6069f38ad5c2473eL, 0xbe656672ae45792cL, 0x79555ffcb891b530L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:8a1ac2af-b452-4f6d-a997-fcde45094820(unimodel.structure)/8742999790642640176");
    b.version(2);
    b.property("description", 0x79555ffcb891b533L).type(PrimitiveTypeId.STRING).origin("8742999790642640179").done();
    b.property("phone", 0x79555ffcb891b535L).type(PrimitiveTypeId.STRING).origin("8742999790642640181").done();
    b.aggregate("address", 0x79555ffcb891b57bL).target(0x6069f38ad5c2473eL, 0xbe656672ae45792cL, 0x79555ffcb891b538L).optional(false).ordered(true).multiple(false).origin("8742999790642640251").done();
    b.aggregate("library", 0x79555ffcb891b59fL).target(0x6069f38ad5c2473eL, 0xbe656672ae45792cL, 0x79555ffcb891b557L).optional(true).ordered(true).multiple(false).origin("8742999790642640287").done();
    b.aggregate("floor", 0x79555ffcb891b5a2L).target(0x6069f38ad5c2473eL, 0xbe656672ae45792cL, 0x79555ffcb891b53bL).optional(false).ordered(true).multiple(true).origin("8742999790642640290").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForClass() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("unimodel", "Class", 0x6069f38ad5c2473eL, 0xbe656672ae45792cL, 0x79555ffcb891b5e6L);
    b.class_(false, false, false);
    b.super_("unimodel.structure.Room", 0x6069f38ad5c2473eL, 0xbe656672ae45792cL, 0x79555ffcb891b5a6L);
    b.origin("r:8a1ac2af-b452-4f6d-a997-fcde45094820(unimodel.structure)/8742999790642640358");
    b.version(2);
    b.property("seats", 0x79555ffcb891b5e7L).type(PrimitiveTypeId.INTEGER).origin("8742999790642640359").done();
    b.property("blackboard", 0x79555ffcb891b5e9L).type(PrimitiveTypeId.INTEGER).origin("8742999790642640361").done();
    b.property("speaker", 0x79555ffcb891b5ecL).type(PrimitiveTypeId.INTEGER).origin("8742999790642640364").done();
    b.property("computer", 0x79555ffcb891b5f0L).type(PrimitiveTypeId.INTEGER).origin("8742999790642640368").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForFloor() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("unimodel", "Floor", 0x6069f38ad5c2473eL, 0xbe656672ae45792cL, 0x79555ffcb891b53bL);
    b.class_(false, false, false);
    b.origin("r:8a1ac2af-b452-4f6d-a997-fcde45094820(unimodel.structure)/8742999790642640187");
    b.version(2);
    b.property("number", 0x79555ffcb891b5afL).type(PrimitiveTypeId.INTEGER).origin("8742999790642640303").done();
    b.property("bathrooms", 0x79555ffcb891b5b1L).type(PrimitiveTypeId.INTEGER).origin("8742999790642640305").done();
    b.aggregate("rooms", 0x79555ffcb891b60eL).target(0x6069f38ad5c2473eL, 0xbe656672ae45792cL, 0x79555ffcb891b5a6L).optional(true).ordered(true).multiple(true).origin("8742999790642640398").done();
    b.aggregate("offices", 0x79555ffcb89c9ee6L).target(0x6069f38ad5c2473eL, 0xbe656672ae45792cL, 0x79555ffcb891b5aeL).optional(true).ordered(true).multiple(true).origin("8742999790643355366").done();
    b.aggregate("classes", 0x79555ffcb89c9ee9L).target(0x6069f38ad5c2473eL, 0xbe656672ae45792cL, 0x79555ffcb891b5e6L).optional(true).ordered(true).multiple(true).origin("8742999790643355369").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForLibrary() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("unimodel", "Library", 0x6069f38ad5c2473eL, 0xbe656672ae45792cL, 0x79555ffcb891b557L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:8a1ac2af-b452-4f6d-a997-fcde45094820(unimodel.structure)/8742999790642640215");
    b.version(2);
    b.property("workstations", 0x79555ffcb891b574L).type(PrimitiveTypeId.INTEGER).origin("8742999790642640244").done();
    b.property("computers", 0x79555ffcb891b576L).type(PrimitiveTypeId.INTEGER).origin("8742999790642640246").done();
    b.aggregate("books", 0x79555ffcb891b604L).target(0x6069f38ad5c2473eL, 0xbe656672ae45792cL, 0x79555ffcb891b57fL).optional(true).ordered(true).multiple(true).origin("8742999790642640388").done();
    b.aggregate("loans", 0x79555ffcb891b606L).target(0x6069f38ad5c2473eL, 0xbe656672ae45792cL, 0x79555ffcb891b58bL).optional(true).ordered(true).multiple(true).origin("8742999790642640390").done();
    b.aggregate("person", 0x79555ffcb8a5fd9fL).target(0x6069f38ad5c2473eL, 0xbe656672ae45792cL, 0x79555ffcb891b5f5L).optional(true).ordered(true).multiple(true).origin("8742999790643969439").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForLoans() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("unimodel", "Loans", 0x6069f38ad5c2473eL, 0xbe656672ae45792cL, 0x79555ffcb891b58bL);
    b.class_(false, false, false);
    b.origin("r:8a1ac2af-b452-4f6d-a997-fcde45094820(unimodel.structure)/8742999790642640267");
    b.version(2);
    b.property("date", 0x79555ffcb891b58cL).type(MetaIdFactory.dataTypeId(0x6069f38ad5c2473eL, 0xbe656672ae45792cL, 0x79555ffcb891b58eL)).origin("8742999790642640268").done();
    b.associate("book", 0x79555ffcb891b609L).target(0x6069f38ad5c2473eL, 0xbe656672ae45792cL, 0x79555ffcb891b57fL).optional(true).origin("8742999790642640393").done();
    b.associate("person", 0x79555ffcb891b60bL).target(0x6069f38ad5c2473eL, 0xbe656672ae45792cL, 0x79555ffcb891b5f5L).optional(true).origin("8742999790642640395").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForOffice() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("unimodel", "Office", 0x6069f38ad5c2473eL, 0xbe656672ae45792cL, 0x79555ffcb891b5aeL);
    b.class_(false, false, false);
    b.super_("unimodel.structure.Room", 0x6069f38ad5c2473eL, 0xbe656672ae45792cL, 0x79555ffcb891b5a6L);
    b.origin("r:8a1ac2af-b452-4f6d-a997-fcde45094820(unimodel.structure)/8742999790642640302");
    b.version(2);
    b.property("type", 0x79555ffcb891b5e1L).type(MetaIdFactory.dataTypeId(0x6069f38ad5c2473eL, 0xbe656672ae45792cL, 0x79555ffcb891b5b4L)).origin("8742999790642640353").done();
    b.property("capacity", 0x79555ffcb891b5e3L).type(PrimitiveTypeId.INTEGER).origin("8742999790642640355").done();
    b.associate("address", 0x79555ffcb891b610L).target(0x6069f38ad5c2473eL, 0xbe656672ae45792cL, 0x79555ffcb891b538L).optional(false).origin("8742999790642640400").done();
    b.aggregate("persons", 0x79555ffcb891b61cL).target(0x6069f38ad5c2473eL, 0xbe656672ae45792cL, 0x79555ffcb891b5f5L).optional(false).ordered(true).multiple(true).origin("8742999790642640412").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForPerson() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("unimodel", "Person", 0x6069f38ad5c2473eL, 0xbe656672ae45792cL, 0x79555ffcb891b5f5L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:8a1ac2af-b452-4f6d-a997-fcde45094820(unimodel.structure)/8742999790642640373");
    b.version(2);
    b.property("category", 0x79555ffcb891b5f6L).type(MetaIdFactory.dataTypeId(0x6069f38ad5c2473eL, 0xbe656672ae45792cL, 0x79555ffcb891b5cdL)).origin("8742999790642640374").done();
    b.property("badge", 0x79555ffcb891b5f8L).type(PrimitiveTypeId.STRING).origin("8742999790642640376").done();
    b.property("age", 0x79555ffcb891b5fbL).type(PrimitiveTypeId.INTEGER).origin("8742999790642640379").done();
    b.property("fiscal_code", 0x79555ffcb891b5ffL).type(PrimitiveTypeId.STRING).origin("8742999790642640383").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForRoom() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("unimodel", "Room", 0x6069f38ad5c2473eL, 0xbe656672ae45792cL, 0x79555ffcb891b5a6L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:8a1ac2af-b452-4f6d-a997-fcde45094820(unimodel.structure)/8742999790642640294");
    b.version(2);
    b.property("dimension", 0x79555ffcb891b5a9L).type(MetaIdFactory.dataTypeId(0x6069f38ad5c2473eL, 0xbe656672ae45792cL, 0x79555ffcb891b597L)).origin("8742999790642640297").done();
    b.property("socket", 0x79555ffcb891b5abL).type(PrimitiveTypeId.INTEGER).origin("8742999790642640299").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForUniversity() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("unimodel", "University", 0x6069f38ad5c2473eL, 0xbe656672ae45792cL, 0x79555ffcb891b526L);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:8a1ac2af-b452-4f6d-a997-fcde45094820(unimodel.structure)/8742999790642640166");
    b.version(2);
    b.property("chancellor", 0x79555ffcb891b52bL).type(PrimitiveTypeId.STRING).origin("8742999790642640171").done();
    b.property("description", 0x79555ffcb891b52dL).type(PrimitiveTypeId.STRING).origin("8742999790642640173").done();
    b.aggregate("buildings", 0x79555ffcb891b579L).target(0x6069f38ad5c2473eL, 0xbe656672ae45792cL, 0x79555ffcb891b530L).optional(false).ordered(true).multiple(true).origin("8742999790642640249").done();
    return b.create();
  }
}
